<template><div><h1 id="科学睡眠" tabindex="-1"><a class="header-anchor" href="#科学睡眠" aria-hidden="true">#</a> 科学睡眠</h1>
<h3 id="sleeping-with-science" tabindex="-1"><a class="header-anchor" href="#sleeping-with-science" aria-hidden="true">#</a> Sleeping with Science</h3>
<blockquote>
<p>来源：<a href="https://www.youtube.com/teded/featured" target="_blank" rel="noopener noreferrer">https://www.youtube.com/teded/featured<ExternalLinkIcon/></a></p>
</blockquote>
<h2 id="原文阅读" tabindex="-1"><a class="header-anchor" href="#原文阅读" aria-hidden="true">#</a> 原文阅读</h2>
<p>We can all have a bad night of sleep, and that's perfectly normal, but how could we try to improve both the quantity and the quality of our sleep? Here are six scientifically grounded tips for better sleep.</p>
<p>The first tip is regularity. Go to bed at the same time and wake up at the same time. Regularity is king, and it will actually anchor your sleep, and improve both the quantity and the quality, no matter whether it's the weekday or the weekend, or even if you've had a bad night of sleep. And the reason is because deep within your brain, you actually have a master 24-hour clock. It expects regularity, and works best under conditions of regularity, including the control of your sleep-wake schedule. Many of us use an alarm to wake up, but very few of us use a to-bed alarm, and that't something that can be helpful.</p>
<p>The next tip is temperature. Keep it cool. It turns out that your brain and your body need to drop their core temperature by about one degree Celsius, or around two to three degress Fahrenheit, in order to initiate sleep and then to stay asleep. And this is the reason that you will always find it easier to fall asleep in a room that's too cold than too hot. So, the current recommendation is to aim for a bedroom temperature of around about 65 degress Fahrenheit, or a little over 18 degress Celsius. It sound cold but could is must be.</p>
<p>The next tip is darkness. We are a dark-deprived society, and in fact, we need darkness specifically in the evening, to trigger the release or a hormone called melatonin. And melatonin helps regulate the healthy timing of our sleep. In the last hour before bed, try to stay away from all of those computer screens, and tablets and phones. Dim down half the lights in your house. You'd actually be quite surprised at how sleepy that can make you feel. If you'd like, you can wear an eye mask, or you can have blackout shades, and that will help best regulate that critical sleep hormone of melatonin.</p>
<p>The next tip is walk it out. Don't stay in bed awake for long periods of time. And the general rule of thumb is if you've been trying to fall asleep and it's been 25 minutes or so, or you've woken up and you can't get back to sleep, after 25 minutes, the recommendation is to get out of bed, and go and do something different. And the reason is because your brain is an incredibly associative device. The brain has learned the association that the bed is this trigger of wakefullness, and we need to break that association. And by getting out of bed, you can go and do something else. Only return to bed when you're sleepy. And in that way, gradually, your brain will relearn the association, that your bed is this place of sound and sonsistent sleep.</p>
<p>The fifth tip is something that we've actually already spoken about in detail in this series, which is the impact of alcohol and caffeine. So, a good rule of thumb here is to try to stay away from caffeine in the afternoon and in the evening, and certainly try not to go to bed too tipsy.</p>
<p>The final tip: have a wind-down routine. I think many of us in the modern world, we expect to be able to dive into bed at night, switch off the light, and we think that sleep is also just like a light switch, that we should immediately be able to fall asleep. Well, unfortunately, sleep isn't quite like that for most of us. Sleep, as a physiological process, is much more similar to landing a plane. It takes time for your brain to gradually descend down onto the firm bedrock of good sleep. In the last 20 minutes before bed or the last half an hour, even the last hour, disenage from your computer and your phone and try to do something relaxing. Find out whatever works for you and when you have found it, stick to that routine.</p>
<p>The last thing I should note is that if you are suffering from a sleep disorder, for example, from insomnia or sleep apnea, then these tips aren't necessarily going to help you. If I was your sports coach, I could give you all of these tips to improve your performance, but if you have a broken ankle, it's not going to make a difference. We have to treat the broken ankle first before we can get back to improving the quality of your performance. And it's the same way with sleep. So, if you think you have a sleep disorder, just go and speak with your doctor. That's the best piece of advice. Where do we stand, then, in all of these conversation about sleep? Well, I think the evidence is clear. We can think of sleep almost like a life-support system. In fact, some may even call sleep a super power.</p>
<h2 id="生词统计" tabindex="-1"><a class="header-anchor" href="#生词统计" aria-hidden="true">#</a> 生词统计</h2>
<table>
<thead>
<tr>
<th>单词</th>
<th>音标</th>
<th>翻译</th>
</tr>
</thead>
<tbody>
<tr>
<td>grounded</td>
<td>grounded</td>
<td>adj. 理性的、理智的、接触地面的； v. 触地；停</td>
</tr>
<tr>
<td>dim</td>
<td>dɪm</td>
<td>adj. 暗淡的、昏暗的、模糊的、看不清的； v.变模糊、变暗淡； n. 笨蛋、傻子</td>
</tr>
<tr>
<td>critical</td>
<td>ˈkrɪtɪkl</td>
<td>adj. 坚定的、批评的、爱挑剔的、危险的、决定性的、评论的</td>
</tr>
<tr>
<td>tipsy</td>
<td>ˈtɪpsi</td>
<td>adj. 微醉略有醉意的、歪曲的、不稳的</td>
</tr>
</tbody>
</table>
<h2 id="翻译" tabindex="-1"><a class="header-anchor" href="#翻译" aria-hidden="true">#</a> 翻译</h2>
<h4 id="we-can-all-have-a-bad-night-of-sleep-and-that-s-perfectly-normal-but-how-could-we-try-to-improve-both-the-quantity-and-the-quality-of-our-sleep-here-are-six-scientifically-grounded-tips-for-better-sleep" tabindex="-1"><a class="header-anchor" href="#we-can-all-have-a-bad-night-of-sleep-and-that-s-perfectly-normal-but-how-could-we-try-to-improve-both-the-quantity-and-the-quality-of-our-sleep-here-are-six-scientifically-grounded-tips-for-better-sleep" aria-hidden="true">#</a> We can all have a bad night of sleep, and that's perfectly normal, but how could we try to improve both the quantity and the quality of our sleep? Here are six scientifically <code v-pre>grounded</code> tips for better sleep.</h4>
<p>我们都有睡不着觉的时候，这很正常，但我们该如何提升睡眠的数量和质量？以下是改善睡眠的6个有科学根据的建议。</p>
<h4 id="the-first-tip-is-regularity-go-to-bed-at-the-same-time-and-wake-up-at-the-same-time-regularity-is-king-and-it-will-actually-anchor-your-sleep-and-improve-both-the-quantity-and-the-quality-no-matter-whether-it-s-the-weekday-or-the-weekend-or-even-if-you-ve-had-a-bad-night-of-sleep-and-the-reason-is-because-deep-within-your-brain-you-actually-have-a-master-24-hour-clock-it-expects-regularity-and-works-best-under-conditions-of-regularity-including-the-control-of-your-sleep-wake-schedule-many-of-us-use-an-alarm-to-wake-up-but-very-few-of-us-use-a-to-bed-alarm-and-that-s-something-that-can-be-helpful" tabindex="-1"><a class="header-anchor" href="#the-first-tip-is-regularity-go-to-bed-at-the-same-time-and-wake-up-at-the-same-time-regularity-is-king-and-it-will-actually-anchor-your-sleep-and-improve-both-the-quantity-and-the-quality-no-matter-whether-it-s-the-weekday-or-the-weekend-or-even-if-you-ve-had-a-bad-night-of-sleep-and-the-reason-is-because-deep-within-your-brain-you-actually-have-a-master-24-hour-clock-it-expects-regularity-and-works-best-under-conditions-of-regularity-including-the-control-of-your-sleep-wake-schedule-many-of-us-use-an-alarm-to-wake-up-but-very-few-of-us-use-a-to-bed-alarm-and-that-s-something-that-can-be-helpful" aria-hidden="true">#</a> The first tip is regularity. Go to bed at the same time and wake up at the same time. Regularity is king, and it will actually anchor your sleep, and improve both the quantity and the quality, no matter whether it's the weekday or the weekend, or even if you've had a bad night of sleep. And the reason is because deep within your brain, you actually have a master 24-hour clock. It expects regularity, and works best under conditions of regularity, including the control of your sleep-wake schedule. Many of us use an alarm to wake up, but very few of us use a to-bed alarm, and that's something that can be helpful.</h4>
<p>第一条建议是规律性。在同一时间睡觉，同一时间醒来。规律就是王道，他会让你的睡眠更稳定，改善睡眠的数量和质量，无论是在工作日还是周末，甚至是你昨晚睡得不好，原因是在你的大脑深处，你有一个24小时的生物钟。它期待规律，并且在规律的条件下工作的更好，包括控制你的睡眠-醒来时间表。我们很多人都用闹钟来叫醒自己，但很少有人在睡觉前用闹钟，这是很有帮助的。</p>
<h4 id="the-next-tip-is-temperature-keep-it-cool-it-turns-out-that-your-brain-and-your-body-need-to-drop-their-core-temperature-by-about-one-degree-celsius-or-around-two-to-three-degress-fahrenheit-in-order-to-initiate-sleep-and-then-to-stay-asleep-and-this-is-the-reason-that-you-will-alaways-find-it-easier-to-fall-asleep-in-a-room-that-s-too-cold-than-too-hot-so-the-current-recommendation-is-to-aim-for-a-bedroom-temperature-of-aroud-about-65-degress-fahrenheit-or-a-little-over-18-degress-celsius-it-sounds-cold-but-cold-it-must-be" tabindex="-1"><a class="header-anchor" href="#the-next-tip-is-temperature-keep-it-cool-it-turns-out-that-your-brain-and-your-body-need-to-drop-their-core-temperature-by-about-one-degree-celsius-or-around-two-to-three-degress-fahrenheit-in-order-to-initiate-sleep-and-then-to-stay-asleep-and-this-is-the-reason-that-you-will-alaways-find-it-easier-to-fall-asleep-in-a-room-that-s-too-cold-than-too-hot-so-the-current-recommendation-is-to-aim-for-a-bedroom-temperature-of-aroud-about-65-degress-fahrenheit-or-a-little-over-18-degress-celsius-it-sounds-cold-but-cold-it-must-be" aria-hidden="true">#</a> The next tip is temperature. Keep it cool. It turns out that your brain and your body need to drop their core temperature by about one degree Celsius, or around two to three degress Fahrenheit, in order to initiate sleep and then to stay asleep. And this is the reason that you will alaways find it easier to fall asleep in a room that's too cold than too hot. So, the current recommendation is to aim for a bedroom temperature of aroud about 65 degress Fahrenheit, or a little over 18 degress Celsius. It sounds cold but cold it must be.</h4>
<p>下一个建议是温度。保持清爽。事实证明，你的大脑和身体需要降低核心温度大约1摄氏度，或大约2-3华氏度以开始睡眠直至睡着。这就是为什么你总是会发现在一个冷的房间里比在一个热的房间里更容易入睡。所以，目前的建议是把卧室的温度控制在华氏65度左右，或略高于18摄氏度。这听起来很冷，但很有必要。</p>
<h4 id="the-next-tip-is-darkness-we-are-a-dark-deprived-society-and-in-fact-we-need-darkness-specifically-in-the-evening-to-trigger-the-release-or-a-hormone-called-melatonin-and-melatonin-helps-regulate-the-healthy-timing-of-our-sleep-in-the-last-hour-before-bed-try-to-stay-away-from-all-of-those-computer-screens-and-tablets-and-phones-dim-down-half-the-lights-in-your-house-you-d-actually-be-quite-surprised-at-how-sleepy-that-can-make-you-feel-if-you-d-like-you-can-wear-an-eye-mask-or-you-can-have-blackout-shades-and-that-will-help-best-regulate-that-critical-sleep-hormone-of-melatonin" tabindex="-1"><a class="header-anchor" href="#the-next-tip-is-darkness-we-are-a-dark-deprived-society-and-in-fact-we-need-darkness-specifically-in-the-evening-to-trigger-the-release-or-a-hormone-called-melatonin-and-melatonin-helps-regulate-the-healthy-timing-of-our-sleep-in-the-last-hour-before-bed-try-to-stay-away-from-all-of-those-computer-screens-and-tablets-and-phones-dim-down-half-the-lights-in-your-house-you-d-actually-be-quite-surprised-at-how-sleepy-that-can-make-you-feel-if-you-d-like-you-can-wear-an-eye-mask-or-you-can-have-blackout-shades-and-that-will-help-best-regulate-that-critical-sleep-hormone-of-melatonin" aria-hidden="true">#</a> The next tip is darkness. We are a dark-deprived society, and in fact, we need darkness specifically in the evening, to trigger the release or a hormone called melatonin. And melatonin helps regulate the healthy timing of our sleep. In the last hour before bed, try to stay away from all of those computer screens, and tablets and phones. <code v-pre>Dim</code> down half the lights in your house. You'd actually be quite surprised at how sleepy that can make you feel. If you'd like, you can wear an eye mask, or you can have blackout shades, and that will help best regulate that <code v-pre>critical</code> sleep hormone of melatonin.</h4>
<p>下一个建议是黑暗。我们生活在缺乏黑暗的社会，事实上，我们在晚上特别需要黑暗，来触发一种叫褪黑激素的释放。褪黑激素帮助我们调节健康的睡眠时间。在睡前的一个小时，尽量远离所有的电脑屏幕、平板电脑和手机。把你房子里一半的灯调暗。你会惊讶的发现这会让你感到多么的困倦。如果你愿意，你可以戴一个艳照或者遮光罩，这将有助于更好的调节褪黑激素的释放。</p>
<h4 id="the-next-tip-is-walk-it-out-don-t-stay-in-bed-awake-for-long-periods-of-time-and-the-general-rule-of-thumb-is-if-you-ve-been-trying-to-fall-asleep-and-it-s-been-25-minutes-or-so-or-you-ve-woken-up-and-you-can-t-get-back-to-sleep-after-25-minutes-the-recommendation-is-to-get-out-of-bed-and-go-and-do-something-different-and-the-reason-is-because-your-brain-is-an-incredibly-associative-device-the-brain-has-learned-the-association-that-the-bed-is-this-trigger-of-wakefullness-and-we-need-to-break-that-association-and-by-getting-out-of-bed-you-can-go-and-do-something-else-only-return-to-bed-when-you-re-sleepy-and-in-that-way-gradually-your-brain-will-relearn-the-association-that-your-bed-is-this-place-of-sound-and-consistent-sleep" tabindex="-1"><a class="header-anchor" href="#the-next-tip-is-walk-it-out-don-t-stay-in-bed-awake-for-long-periods-of-time-and-the-general-rule-of-thumb-is-if-you-ve-been-trying-to-fall-asleep-and-it-s-been-25-minutes-or-so-or-you-ve-woken-up-and-you-can-t-get-back-to-sleep-after-25-minutes-the-recommendation-is-to-get-out-of-bed-and-go-and-do-something-different-and-the-reason-is-because-your-brain-is-an-incredibly-associative-device-the-brain-has-learned-the-association-that-the-bed-is-this-trigger-of-wakefullness-and-we-need-to-break-that-association-and-by-getting-out-of-bed-you-can-go-and-do-something-else-only-return-to-bed-when-you-re-sleepy-and-in-that-way-gradually-your-brain-will-relearn-the-association-that-your-bed-is-this-place-of-sound-and-consistent-sleep" aria-hidden="true">#</a> The next tip is walk it out. Don't stay in bed awake for long periods of time. And the general rule of thumb is if you've been trying to fall asleep and it's been 25 minutes or so, or you've woken up and you can't get back to sleep, after 25 minutes, the recommendation is to get out of bed, and go and do something different. And the reason is because your brain is an incredibly associative device. The brain has learned the association that the bed is this trigger of wakefullness, and we need to break that association. And by getting out of bed, you can go and do something else. Only return to bed when you're sleepy. And in that way, gradually, your brain will relearn the association, that your bed is this place of sound and consistent sleep.</h4>
<p>下一个建议是走出去。醒了就不要长时间躺在床上。一般的情况是，如果你已经尝试入睡了25分钟，或者你醒来后无法再入睡，25分钟后，建议你起床，去做一些其他事情。原因是你的大脑是一个难以置信的联想装置。大脑已经认识到，床是唤醒人清醒的诱因，我们需要打破这种联系。起床之后，你可以去做其他的事情。只有在感到困倦的时候才回到床上。这样你的大脑就会重新认识到，床是让你安稳睡觉的地方。</p>
<h4 id="the-fifth-tip-is-something-that-we-ve-actually-already-spoken-about-in-detail-in-this-series-which-is-the-impact-of-alcohol-and-caffeine-so-a-good-rule-of-thumb-here-is-to-try-to-stay-away-from-caffeine-in-the-afternoon-and-in-the-evening-and-certainly-try-not-to-go-to-bed-too-tipsy" tabindex="-1"><a class="header-anchor" href="#the-fifth-tip-is-something-that-we-ve-actually-already-spoken-about-in-detail-in-this-series-which-is-the-impact-of-alcohol-and-caffeine-so-a-good-rule-of-thumb-here-is-to-try-to-stay-away-from-caffeine-in-the-afternoon-and-in-the-evening-and-certainly-try-not-to-go-to-bed-too-tipsy" aria-hidden="true">#</a> The fifth tip is something that we've actually already spoken about in detail in this series, which is the impact of alcohol and caffeine. So, a good rule of thumb here is to try to stay away from caffeine in the afternoon and in the evening, and certainly try not to go to bed too <code v-pre>tipsy</code>.</h4>
<p>第五个建议我们已经在这个系列中详细讨论过了，那就是酒精和咖啡因的影响。所以，一个很好的经验法则就是尽量不要在下午和晚上喝咖啡，当然也不要喝的酩酊大醉上床。</p>
<h4 id="the-final-tip-have-a-wind-down-routine-i-think-many-of-us-in-the-modern-world-we-expect-to-be-able-to-dive-into-bed-at-night-switch-off-the-light-and-we-think-that-sleep-is-also-just-like-a-light-switch-that-we-should-immediately-be-able-to-fall-asleep-well-unfortunately-sleep-isn-t-quite-like-that-for-most-of-us-sleep-as-a-physiological-process-is-much-more-similar-to-landing-a-plane-it-takes-time-for-your-brain-to-gradually-descend-down-onto-the-firm-bedrock-of-good-sleep-in-the-last-20-minutes-before-bed-or-the-last-half-an-hour-even-the-last-hour-disengage-from-your-computer-and-your-phone-and-try-do-to-something-relaxing-find-out-whatever-works-for-you-and-when-you-have-found-it-stick-to-that-routine" tabindex="-1"><a class="header-anchor" href="#the-final-tip-have-a-wind-down-routine-i-think-many-of-us-in-the-modern-world-we-expect-to-be-able-to-dive-into-bed-at-night-switch-off-the-light-and-we-think-that-sleep-is-also-just-like-a-light-switch-that-we-should-immediately-be-able-to-fall-asleep-well-unfortunately-sleep-isn-t-quite-like-that-for-most-of-us-sleep-as-a-physiological-process-is-much-more-similar-to-landing-a-plane-it-takes-time-for-your-brain-to-gradually-descend-down-onto-the-firm-bedrock-of-good-sleep-in-the-last-20-minutes-before-bed-or-the-last-half-an-hour-even-the-last-hour-disengage-from-your-computer-and-your-phone-and-try-do-to-something-relaxing-find-out-whatever-works-for-you-and-when-you-have-found-it-stick-to-that-routine" aria-hidden="true">#</a> The final tip: have a wind-down routine. I think many of us in the modern world, we expect to be able to dive into bed at night, switch off the light, and we think that sleep is also just like a light switch, that we should immediately be able to fall asleep. Well, unfortunately, sleep isn't quite like that for most of us. Sleep, as a physiological process, is much more similar to landing a plane. It takes time for your brain to gradually descend down onto the firm bedrock of good sleep. In the last 20 minutes before bed or the last half an hour, even the last hour, disengage from your computer and your phone and try do to something relaxing. Find out whatever works for you and when you have found it, stick to that routine.</h4>
<p>最后一个建议：找到一个渐进的方式。当今社会，我们都希望能够在晚上钻进被窝，关掉灯，我们以为睡眠就像电灯开关一样，应该能马上睡觉。这肯定是不行的，睡眠对我们大多数人来说都不是这样的。睡眠，是一种生理过程，更像是飞机着陆。你的大脑需要一段时间才能下降到良好睡眠的坚实基础上。在睡前的最后20分钟，或者最后半小时，甚至最后一个小时，远离你的电脑和手机，尝试做一些能放松的事。找出对自己有效的方法，并坚持下去。</p>
<h4 id="the-last-thing-i-should-note-is-that-if-you-are-suffering-from-a-sleep-disorder-for-example-from-insomnia-or-sleep-apnea-then-these-tips-aren-t-necessarily-going-to-help-you-if-i-was-your-sports-coach-i-could-give-you-all-of-these-tips-to-improve-your-performance-but-if-you-have-a-broken-ankle-it-s-not-going-to-make-a-difference-we-have-to-treat-the-broken-ankle-first-before-we-can-get-back-to-improving-the-quality-of-your-performance-and-it-s-the-same-way-with-sleep-so-if-you-think-you-have-a-sleep-disorder-just-go-and-speak-with-your-doctor-that-s-the-best-piece-of-advice-where-do-we-stand-then-in-all-of-this-conversation-about-sleep-well-i-think-the-evidence-is-clear-we-can-think-of-sleep-almost-like-a-life-support-system-in-fact-some-may-even-call-sleep-a-super-power" tabindex="-1"><a class="header-anchor" href="#the-last-thing-i-should-note-is-that-if-you-are-suffering-from-a-sleep-disorder-for-example-from-insomnia-or-sleep-apnea-then-these-tips-aren-t-necessarily-going-to-help-you-if-i-was-your-sports-coach-i-could-give-you-all-of-these-tips-to-improve-your-performance-but-if-you-have-a-broken-ankle-it-s-not-going-to-make-a-difference-we-have-to-treat-the-broken-ankle-first-before-we-can-get-back-to-improving-the-quality-of-your-performance-and-it-s-the-same-way-with-sleep-so-if-you-think-you-have-a-sleep-disorder-just-go-and-speak-with-your-doctor-that-s-the-best-piece-of-advice-where-do-we-stand-then-in-all-of-this-conversation-about-sleep-well-i-think-the-evidence-is-clear-we-can-think-of-sleep-almost-like-a-life-support-system-in-fact-some-may-even-call-sleep-a-super-power" aria-hidden="true">#</a> The last thing I should note is that if you are suffering from a sleep disorder, for example, from insomnia or sleep apnea, then these tips aren't necessarily going to help you. If I was your sports coach, I could give you all of these tips to improve your performance, but if you have a broken ankle, it's not going to make a difference. We have to treat the broken ankle first before we can get back to improving the quality of your performance. And it's the same way with sleep. So, if you think you have a sleep disorder, just go and speak with your doctor. That's the best piece of advice. Where do we stand, then, in all of this conversation about sleep? Well, I think the evidence is clear. We can think of sleep almost like a life-support system. In fact, some may even call sleep a super power.</h4>
<p>最后我要说明的是，如果你患有睡眠障碍，比如失眠或睡眠呼吸暂停症，那么这些建议不一定对你有帮助。如果我是你的健身教练，我可以给你提供建议来提高比赛成绩，但如果你的脚踝骨折了，我们必须先治疗你的脚踝，然后才考虑提高你的比赛成绩。睡眠也是如此，如果你认为你有睡眠障碍，去找你的医生谈谈。这是最好建议。那么在所有关于睡眠的谈话中，我们的立场是什么？我认为证据很清楚。我们可以把睡眠看作是维持生命的系统。事实上，有些人甚至称睡眠是一种超能力。</p>
<src-rtyAudio :src="`https://rtyxmd.gitee.io/rtyresources2020/September/Sleeping%20with%20Science.mp3`"></src-rtyAudio></div></template>
