<template><div><h1 id="diving-under" tabindex="-1"><a class="header-anchor" href="#diving-under" aria-hidden="true">#</a> Diving Under</h1>
<blockquote>
<p>By Wendelin Van Draneen</p>
</blockquote>
<p>All I've ever wanted is for Juli Baker to leave me alone. For her to back off —— you know, just give me some space.</p>
<p>It all started the summer before second grade when our moving van pulled into her neighborhood. And since we're now about done with the eighth grade, that, my friend, makes more than half a decade of strategic avoidance and social discomfort.</p>
<p>She didn't just barge into my life. She barged and shoved and wedged her way into my life. Did we invite her to get into our moving van and start climbing all over boxes? No! But that's exactly what she did, taking over and showing off like only Juli Baker can.</p>
<p>My dad tried to stop her. &quot;Hey!&quot; he says as she's catapulting herself on board. &quot;What are you doing? You are getting mud everywhere!&quot; So true, too. Her shoes were, like, caked with the stuff.</p>
<p>She didn't hop out, though. Instead, she planted her rear end on the floor and started pushing a big box with her feet. &quot;Don't you want some help?&quot; She glanced my way. &quot;It sure looks like you need it.&quot;</p>
<p>I didn't like the imlication. And even though my dad had been tossing me the same sort of look all week, I could tell —— he didn't like this girl either. &quot;Hey! Don't do that,&quot; he warned her. &quot;There are some really valuable things in that box.&quot;</p>
<p>&quot;Oh. Well, how about this one?&quot; She scoots over to a box labeled LENOX and looks my way again. &quot;We should push it together!&quot;</p>
<p>&quot;No, no, no!&quot; my dad says, then pulls her up by the arm. &quot;Why don't you run along home? Your mother's probably wondering where you are.&quot;</p>
<p>This was the beginning of my soon-to-become-acute awareness that hte girl cannt take a hint. Of any kind. Dose she zip on home like a kid should when they've been invited to leave? No. She says, &quot;Oh, my mom knows where I am. She said it was fine.&quot; Then she points across the street and says, &quot;We just live right over there.&quot;</p>
<p>My father looks to where she's pointing and mutters, &quot;Oh baby.&quot; Then he looks at me and winks as he says, &quot;Bryce, isn't it time for you to go inside and help your mother?&quot;</p>
<p>I knew right off that this was a ditch play. And I didn't think about it until later, but ditch wasn't a play I'd run with my dad before. Face it, pulling a ditch is not something discussed with dads. It's like, against parental law to tell your kid it's okay to ditch someone, no matter how annoying or muddy they might be.</p>
<p>But there he was, putting the play in motion, and man, he didn't have to wink twice. I smiled and said, &quot;Sure thing!&quot; then jumped off the liftgate and headed for my new front door.</p>
<p>I heard her coming after me but I couldn't belive it. Maybe it just sounded like she was chasing me; maybe she was really going the other way. But before I got up the never to look, she blasted right past me, grabbing my arm and yanking me along.</p>
<p>This was too much. I planted myself and was about to tell her to get lost when the weirdest thing happened. I was making this big windmill motion to break away from her, but somehow on the downswimg my hand wound up tangling into hers. I couldn't believe it. There I was, holding the mud monkey's hand!</p>
<p>I tried to shake her off, but she just clamped on tight and yanked me along, saying, &quot;C'mon!&quot;</p>
<p>My mom came out of the house and immediately got the world's sappiest look on her face. &quot;Well, hello,&quot; she says to Juli.</p>
<p>&quot;Hi!&quot;</p>
<p>I'm still trying to pull free, but the girl's got me in a death grip. My mom's grinning, looking at our hands and my fiery red face. &quot;And what's your name, honey?&quot;</p>
<p>&quot;Julianna Baker. I live right over there,&quot; she says, pointing with her unoccupied hand.</p>
<p>&quot;Well, I see you've met my son,&quot; she says, still grinning away.</p>
<p>&quot;Uh-huh!&quot;</p>
<p>Finally I break free and do the only manly thing available when you're seven years old —— I dive behind my mother.</p>
<p>Mom puts her arm around me and says, &quot;Bryce, honey, why don't you show Julianna around the house?&quot;</p>
<p>I flash her help and warning signals with every part of my body, but she's not receiving. Then she shakes me off and says, &quot;Go on.&quot;</p>
<p>Juli would've tramped right in if my mother hadn't noticed her shoes and told her to take them off. And after those were off, my mom told her that her dirty socks had to go, too. Juli wasn't embarrassed. Not a bit. She just peeled them off and left them in a crusty heap on our porch.</p>
<p>I didn't exactly give her a tour. I locked myself in the bathroom instead. And after about ten minutes of yelling back at her that no, I wan't coming out anytime soon, things got quiet out in the hall. Another ten minutes went by before I got the nerve to peek out the door.</p>
<p>No Juli. I snuck out and looked around, and yes! She was gone.</p>
<p>Not a very sophisticated ditch, but hey, I was only seven.</p>
<p>My troubles were far from over, though. Every day she come back, over and over again. &quot;Can Bryce play?&quot; I could hear her asking from my hiding place behind the couch. &quot;Is he ready yet?&quot; One time she even cut across the yard and looked through my window. I spooted her in the nick of time and dove under my bed, but man, that right there tells you something about Juli Baker. She's got no comcept of personal space. No respect for privacy. The world is her playground, and watch out below —— Jili's on the slide!</p>
<p>Lucky for me, my dad was willing to run block. And he did it over and over again. He told her I was busy or sleeping or just plain gone. He was a lifesaver.</p>
<p>My sister, on the other hand, tried to sabotage me any chance she got. Lynetta's like that. She's four years older than me, and buddy, I've learned from watching her how not to run your life. She's got ANTAGONIZE written all over her. Just look at her —— not cross-eyed or with your tongue sticking out or anything —— just look at her and you've started an argument.</p>
<p>I used to knock-down-drag-out with her, but it's just not worth it. Girls don't fight fair. They pull your hair and gouge you and pinch you; then they run off gasping to mommy when you try and defend yourself with a fist. Then you get locked into time-out, and for what? No, my friend, the secret is, don't snap at the bait. Let it dangle. Swim around it. Laugh it off. After a while they'll give up and try to lure someone else.</p>
<p>At least that's the way it is with Lynetta. And the bonus of having her as a pain-in-the-rear sister was figuring out that this method works on everyone. Teacher, jerks at school, even Mom and Dad. Seriously. There's no winning arguments with your parents, so why get all pumped up over them? It is way better do dive down and get out of the way than it is to get clobbered by some parental tidal wave.</p>
<p>The funny thing is, Lynetta's still clueless when it comes to dealing with Mom and Dad. She goes straight into thrash mode and is too busy drowning in the argument to take a deep breath and dive for calmer water.</p>
<p>And she thinks I'm stupid.</p>
<p>Anyway, true to form, Lynetta tried to bait me with Juli those first few days. She even snuck her past Dad once and marched her all around the house, hunting me down. I wedged myself up on the top shelf of my closet, and lucky for me, neither of them looked up. A few minutes later I heard Dad yell at Juli to get off the antique furniture, and once again, she got booted.</p>
<p>I don't think I went outside that whole first week. I helped unpack stuff and watched TV and just kind of hung around while my mom and dad arranged and rearranged the furniture, debating whether Empire settees and French Rococo tables should even be put in the same room.</p>
<p>So believe me, I was dying to go outside. But every time I checked through the window, I could see Juli showing off in her yard. She'd heading a soccer ball or doing high kicks with it or dribbling it up and down their driveway. And when she wasn't busy showing off, she'd just sit on the curb with ball between her feet, staring at our house.</p>
<p>My mom didn't understand why it was so awful that &quot;that cute little girl&quot; had held my hand. She thought I should make friends with her. &quot;I thought you like soccer, honey. Why don't you go out there and kick the ball around?&quot;</p>
<p>Because I didn't want to be kicked around, that's why. And although I couldn't say it like that at the time, I still had enough sense at age seven and a half to know that Juli Baker was dangerous.</p>
<p>Unavoidably dangerous, as it turns out. The minute I walked into Mrs. Yelson's second-grade classroom, I was dead meat. &quot;Bryce!&quot; Juli squeals. &quot;You're here.&quot; Then she charges across the room and tackles me.</p>
<p>Mrs. Yelson tried to explain this attack away as a &quot;welcome hub,&quot; but man, that was no hug. That was a front-line, take-'em-down tackle. And even though I shook her off, it was too late. I was branded for life. Everyone jeered, &quot;Where's your girl friend, Bryce?&quot; &quot;Are you married yet, Bryce?&quot; And then when she chased me around at recess and tried to lay kisses on me, the whole school started singing, &quot;Bryce and Juli sitting in a tree, K-I-S-S-I-N-G...&quot;</p>
<p>My first year in town was a disaster.</p>
<p>Third grade wasn't much better. She was still hot on my trail every time I turned around. Same with fourth. But then in fifth grade I took action.</p>
<p>It started out slow —— one of those Nah-that's-not-right ideas you get and forget. But the more I played with the idea, the more I thought, What better way to ward Juli off? What better way to say to her, &quot;Juli, you are not my type&quot;?</p>
<p>And so, my friend, I hatched the plan.</p>
<p>I asked Shelly Stalls out.</p>
<p>To fully appreciate the brilliance of this, you have to understand that Juli hates Shelly Stalls. She always has, though it beats me why. Shelly's nice and she's friendly and she's got a lot of hair. What's not to like? But Juli hated her, and I was going to make this little gem of knowledge the solution to my problem.</p>
<p>What I was thinking was that Shelly would eat lunch at our table and maybe walk around a little with me. That way, anytime Juli was around, all I'd have to do was hang a little closer to Shelly and things would just naturally take care of themselves. What happened, though, is that Shelly took things way too seriously. She went around telling everybody —— including Juli —— that we were in love.</p>
<p>In no time Juli and Shelly got into some kind of catfight, and while Shelly was recovering from that, my supposed friend Garrett —— who had been totally behind this plan —— told her what I was up to. He's always denid it, but I've since learned that his code of honor is easily corrupted by weepy femals.</p>
<p>That afternoon the principal tried cross-examining me, but I wouldn't cop to anything. I just kept telling her that I was sorry and that I really didn't under stand what had happened. Finally she let me go.</p>
<p>Shelly cried for days and followed me around school sniffling and making me feel kie a real jerk, which was even worse than having Juli as a shadow.</p>
<p>Everything blew over at the one-week mark, though, when Shelly officially dumped me and started going out with Kyle Larsen. Then Juli started up with the goo-goo eyes again, and I was back to square one.</p>
<p>Now, in sixth grade things changed, though whether whey improved is hard to say. I don't remember Juli actually chasing me in the sixth grade. But I do remember her sniffing me.</p>
<p>Yes, my friend, I said sniffing.</p>
<p>And you can blame that on our teacher, Mr. Mertins. He stuck Juli to me like glue. Mr. Mertins has got some kind of doctorate in seating arrangements or something, because he analyzed and scrutinized and practically baptized the seats we had to sit in. And of course he decided to seat Juli right next to me.</p>
<p>Juli Baker is the kind of annoying person who makes a point of letting you know she's smart. Her hand is the first one up; her answers are usually complete dissertations; her project are always turned in early and used as weapons against the rest of the class. Teachers always have to told her project up and say, &quot;This is what I'm looking for, class. This is an example of A-plus work.&quot; Add all the extra credit she does to an already perfect score, and I swear she's never gotten less than 120 percent in any subject.</p>
<p>But after Mr. Mertins stuck Juli right next to me, her annoying knowledge of all subjects far and wide come in handy. See, suddenly Juli's perfect answers, written in perfect cursive, were right across the aisle, just an eye-shot away. You wouldn't believe the number of answer I snagged from her. I started getting A's and B's on everything! it was great!</p>
<p>But then Mr. Mertins pulled the shift. He had some new idea for &quot;optimizing positional latitude and longitude,&quot; and when the dus finally settled, I was sitting right in front of Juli Baker.</p>
<p>This is where the sniffing comes in. That maniac started leaning forward and sniffing my hair. She'd edge her nose practically up to my scalp and sniff-sniff-sniff.</p>
<p>I tried elbowing and back-kicking. I tried scooting my chair way forward or putting my backpack between me and the seat. Nothing helped. She'd just scoot up, too, or lean over a little farther and sniff-sniff-sniff.</p>
<p>I finally asked Mr. Mertins to move me, but he wouldn't do it. Something about not wanting to diturb the delicate balance of educational energies.</p>
<p>Whatever. I was stuck with her sniffing. And since I couldn't see her perfectly penned answers anymore, my grade took a dive. Especially in spelling.</p>
<p>Then one time, during a test, Juli's in the middle of sniffing my hair when she notices that I've blown a spelling word. A lot of words. Suddenly the sniffing stops and the whispering starts. At first I coundn't believe it. Juli Baker cheating? But sure enough, she was spelling words for me, right in my ear.</p>
<p>Juli'd always been sly about sniffing, which really bugged me because no one ever noticed her doing it, but she was just as sly about giving me answers, which was okay by me. The bad thing about it was that I started counting on her spelling in my ear. I mean, why study when you don't have to, right? But after a while, taking all those answers made me feel sort of indebted to her. How can you tell someone to bug off or quit sniffing you when you owe them? It's, you know, wrong.</p>
<p>So I spent the sixth grade somewhere between uncomfortable and unhappy, but I kept thinking that next year, next year, things would be different. We'd be in junior high —— a big school —— in different classes. It would be a world with too many people to worry about ever seeing Juli Baker again.</p>
<p>It was finally, finally going to be over.</p>
</div></template>
