<template><div><h1 id="如果木星吞噬了地球怎么办" tabindex="-1"><a class="header-anchor" href="#如果木星吞噬了地球怎么办" aria-hidden="true">#</a> 如果木星吞噬了地球怎么办</h1>
<h3 id="what-if-jupiter-swallowed-earth" tabindex="-1"><a class="header-anchor" href="#what-if-jupiter-swallowed-earth" aria-hidden="true">#</a> What If Jupiter Swallowed Earth</h3>
<blockquote>
<p>来源：<a href="https://www.youtube.com/c/WhatIfScienceShow" target="_blank" rel="noopener noreferrer">https://www.youtube.com/c/WhatIfScienceShow<ExternalLinkIcon/></a></p>
</blockquote>
<h2 id="原文阅读" tabindex="-1"><a class="header-anchor" href="#原文阅读" aria-hidden="true">#</a> 原文阅读</h2>
<p>The Earth has been hurtling towards Jupiter for the past 242 days, and now it's about to make impact. Now we're so close to the giant planet that it's the only thing that fills our sky. Ground temperatures on Earth are rising uncontrollably, our atmosphere is igniting into flames, and the scientific community is scrambling to provide answers.</p>
<p>What will happen when the two planets collide? Is there any chance that we could pass right through the gas planet? And, how would this collision transform Jupiter forever? This is What If, and here is what would happen, if Jupiter swallowed Earth.</p>
<p>One way that scientists could find answers would be by looking into the past, because this wouldn't be the first time that Jupiter has collided with another planet. Nearly 4.5 billion years ago, Jupiter was involved in a violent collision with a planet ten times the mass of the Earth. In that case, the collision completely transformed Jupiter's core. But what happened to the other planet? And what can that tell us about our own planet's chances of surviving a crash into the gas giant?</p>
<p>To get some answers, let's travel back to 4.5 billion years ago, when Jupiter was just a young planet trying to find its place in the Universe. Back then, Jupiter's gravitational pull became 30 times more powerful in just a fraction of a million years. This destabilized the orbits of nearby infant planets, and caused some of them to crash into Jupiter.</p>
<p>It's believed that one such planet was 10 times the mass of Earth, and it was mainly a silicate ice core. The planet hit Jupiter with an impact speed of 46 km/s. Jupiter only lost a small amount of mass from the collision, but it's original core was completely changed.</p>
<p>Before the impact, Jupiter had a dense central core of heavy elements, and the rest of the planet was made up of hydrogen and helium. After the impact, the infant planet's silicate ice core merged with Jupiter's, causing Jupiter's core to become diluted. The heavy elements spread out and mixed with the outer layers of Jupiter.</p>
<p>While this collision was a defining moment for Jupiter, it meant the end of the road for the other planet. So what are the odds that Earth's fate would be any different? Well, let's find out.</p>
<p>The Earth orbits around the Sun at an average velocity of 29.78 km/s. At this speed, if the Earth were to just leave its orbit around the Sun and head straight for Jupiter, it would take about 242 days to get there. Throughout our journey, Jupiter would shine like a bright star, growing bigger day by day, hour by hour.</p>
<p>By day 6, Jupiter would appear as bright as our moon. Soon we would start to notice our daylight becoming dimmer. We'll only get about 50 percent of our normal sunlight when we reach Mars's orbit. Luckily for us, the earth's atmosphere would act as a buffer, so we wouldn't experience the cold right away. But that will only last a while, so you'll need to invest in some heavy-duty winter gear. To put it in perspective, Mars has a surface temperature of -63℃, so that's basically what we'd have to look forward to.</p>
<p>Once we speed through Mars's orbit, we'll pass through the asteroid belt. We'll get to see beautiful meteor showers lighting up the sky, but we'll also be at risk with colliding with some of those meteors, so let's keep moving.</p>
<p>After 242 days of traveling through our Solar System, we would finally reach our destination: Jupiter. As the Earth is pulled into Jupiter, our planet's velocity could increase until it reaches 60 km/s. That's 250 times faster than an airplane flies, so you'll want to hold on tight. Oh, and did we mention that Jupiter has 79 confirmed moons orbiting it at all times? So there's a serious risk that we could collide with any of them as the Earth is pulled in closer. And if we do happen to avoid all those moons, things will only get worse.</p>
<p>As we crash into Jupiter, both planets' atmospheres will be compressed, rapidly increasing the temperature, and essentially setting the air on fire. But at least we won't have to worry about colliding with Jupiter's core, because we'll never make it there. Our planet is too small and would burn up in the atmosphere before that ever happens. But this would have a huge impact on Jupiter, as the Earth's remains would completely mix into it's atmosphere.</p>
<p>So if you ever notice our planet going off course and heading towards Jupiter, you might want to jump off along the way. Maybe right as we pass over Mars.</p>
<h2 id="生词统计" tabindex="-1"><a class="header-anchor" href="#生词统计" aria-hidden="true">#</a> 生词统计</h2>
<table>
<thead>
<tr>
<th>单词</th>
<th>音标</th>
<th>翻译</th>
</tr>
</thead>
<tbody>
<tr>
<td>hurtle</td>
<td>ˈhɜːrtl</td>
<td>v. 猛冲、猛烈碰撞、猛投、冲向； n. 碰撞</td>
</tr>
<tr>
<td>ignite</td>
<td>ɪɡˈnaɪt</td>
<td>v. 点燃、使燃烧、使激动、点火、燃烧</td>
</tr>
<tr>
<td>fraction</td>
<td>ˈfrækʃn</td>
<td>n. 分数、部分、小部分、稍微</td>
</tr>
<tr>
<td>silicate</td>
<td>ˈsɪlɪkeɪt</td>
<td>n. [矿物]硅酸盐</td>
</tr>
<tr>
<td>dense</td>
<td>dens</td>
<td>adj. 稠密的、浓厚的、愚钝的</td>
</tr>
<tr>
<td>hydrogen</td>
<td>ˈhaɪdrədʒən</td>
<td>n. [化学]氢</td>
</tr>
<tr>
<td>helium</td>
<td>ˈhiːliəm</td>
<td>n. [化学]氦 （符号为He，2号元素）</td>
</tr>
<tr>
<td>dilute</td>
<td>daɪˈluːt</td>
<td>v. 稀释、冲淡、削弱； adj. 稀释的、淡的</td>
</tr>
<tr>
<td>meteor</td>
<td>ˈmiːtiər</td>
<td>n. 流星、[气象]大气现象</td>
</tr>
<tr>
<td>compress</td>
<td>kəmˈpres</td>
<td>v. 受压缩小、压缩、压紧、精简</td>
</tr>
</tbody>
</table>
<h2 id="翻译" tabindex="-1"><a class="header-anchor" href="#翻译" aria-hidden="true">#</a> 翻译</h2>
<h4 id="the-earth-has-been-hurtling-towards-jupiter-for-the-past-242-days-and-now-it-s-about-to-make-impact-now-we-re-so-close-to-the-giant-planet-that-it-s-the-only-thing-that-fills-our-sky-ground-temperatures-on-earth-are-rising-uncontrollably-our-atmosphere-is-igniting-into-flames-and-the-scientific-community-is-scrambling-to-provide-answers" tabindex="-1"><a class="header-anchor" href="#the-earth-has-been-hurtling-towards-jupiter-for-the-past-242-days-and-now-it-s-about-to-make-impact-now-we-re-so-close-to-the-giant-planet-that-it-s-the-only-thing-that-fills-our-sky-ground-temperatures-on-earth-are-rising-uncontrollably-our-atmosphere-is-igniting-into-flames-and-the-scientific-community-is-scrambling-to-provide-answers" aria-hidden="true">#</a> The Earth has been <code v-pre>hurtling</code> towards Jupiter for the past 242 days, and now it's about to make impact. Now we're so close to the giant planet that it's the only thing that fills our sky. Ground temperatures on Earth are rising uncontrollably, our atmosphere is <code v-pre>igniting</code> into flames, and the scientific community is scrambling to provide answers.</h4>
<p>在过去的242天里，地球一直朝着木星飞驰，现在它就要对木星产生影响了。现在我们离这颗巨大的行星如此之近，以至于它占满了整个天空。地球表面温度正在不可控制的上升，我们的大气层正在燃烧，科学界正在争先恐后地提供答案。</p>
<h4 id="what-will-happen-when-the-two-planets-collide-is-there-any-chance-that-we-could-pass-right-through-the-gas-planet-and-how-would-this-collision-transform-jupiter-forever-this-is-what-if-and-here-is-what-would-happen-if-jupiter-swallowed-earth" tabindex="-1"><a class="header-anchor" href="#what-will-happen-when-the-two-planets-collide-is-there-any-chance-that-we-could-pass-right-through-the-gas-planet-and-how-would-this-collision-transform-jupiter-forever-this-is-what-if-and-here-is-what-would-happen-if-jupiter-swallowed-earth" aria-hidden="true">#</a> What will happen when the two planets collide? Is there any chance that we could pass right through the gas planet? And, how would this collision transform Jupiter forever? This is What If, and here is what would happen, if Jupiter swallowed Earth.</h4>
<p>当两颗行星相撞时会发生什么？我们有可能穿过这颗气体行星吗？而且，这次碰撞将如何永远改变木星？这就是将要发生的事情，如果木星吞噬了地球。</p>
<h4 id="one-way-that-scientists-could-find-answers-would-be-by-looking-into-the-past-because-this-wouldn-t-be-the-first-time-that-jupiter-has-collided-with-another-planet-nearly-4-5-billion-years-ago-jupiter-was-involved-in-a-violent-collision-with-a-planet-ten-times-the-mass-of-the-earth-in-that-case-the-collision-completely-transformed-jupiter-s-core-but-what-happened-to-the-other-planet-and-what-can-that-tell-us-about-our-own-planet-s-chances-of-surviving-a-crash-into-the-gas-giant" tabindex="-1"><a class="header-anchor" href="#one-way-that-scientists-could-find-answers-would-be-by-looking-into-the-past-because-this-wouldn-t-be-the-first-time-that-jupiter-has-collided-with-another-planet-nearly-4-5-billion-years-ago-jupiter-was-involved-in-a-violent-collision-with-a-planet-ten-times-the-mass-of-the-earth-in-that-case-the-collision-completely-transformed-jupiter-s-core-but-what-happened-to-the-other-planet-and-what-can-that-tell-us-about-our-own-planet-s-chances-of-surviving-a-crash-into-the-gas-giant" aria-hidden="true">#</a> One way that scientists could find answers would be by looking into the past, because this wouldn't be the first time that Jupiter has collided with another planet. Nearly 4.5 billion years ago, Jupiter was involved in a violent collision with a planet ten times the mass of the Earth. In that case, the collision completely transformed Jupiter's core. But what happened to the other planet? And what can that tell us about our own planet's chances of surviving a crash into the gas giant?</h4>
<p>科学家们找到答案的一种方法是研究过去，因为这不是木星第一次和另一个行星相撞。大约45亿年前，木星与一颗质量是地球10倍的行星发生了猛烈的碰撞。在这种情况下，这次碰撞完全改变了木星的核心。但是另一个星球发生了什么？这能告诉我们什么，地球在撞击这颗气态巨星时幸存下来的机会有多大？</p>
<h4 id="to-get-some-answers-let-s-travel-back-to-4-5-billion-years-ago-when-jupiter-was-just-a-young-planet-trying-to-find-its-place-in-the-universe-back-then-jupiter-s-gravitational-pull-became-30-times-more-powerful-in-just-a-fraction-of-a-million-years-this-destabilized-the-orbits-of-nearby-infant-planets-and-caused-some-of-them-to-crash-into-jupiter" tabindex="-1"><a class="header-anchor" href="#to-get-some-answers-let-s-travel-back-to-4-5-billion-years-ago-when-jupiter-was-just-a-young-planet-trying-to-find-its-place-in-the-universe-back-then-jupiter-s-gravitational-pull-became-30-times-more-powerful-in-just-a-fraction-of-a-million-years-this-destabilized-the-orbits-of-nearby-infant-planets-and-caused-some-of-them-to-crash-into-jupiter" aria-hidden="true">#</a> To get some answers, let's travel back to 4.5 billion years ago, when Jupiter was just a young planet trying to find its place in the Universe. Back then, Jupiter's gravitational pull became 30 times more powerful in just a <code v-pre>fraction</code> of a million years. This destabilized the orbits of nearby infant planets, and caused some of them to crash into Jupiter.</h4>
<p>为了得到一些答案，让我们回到45亿年前，那时木星只是一个年轻的行星，试图在宇宙中找到自己的位置。那时，木星的引力在短短一百万年的时间里就增加了30倍。这使得附近的新生行星的轨道不稳定，并导致其中一些行星撞向木星。</p>
<h4 id="it-s-believed-that-one-such-planet-was-10-times-the-mass-of-earth-and-it-was-mainly-a-silicate-ice-core-the-planet-hit-jupiter-with-an-impact-speed-of-46-km-s-jupiter-only-lost-a-small-amount-of-mass-from-the-collision-but-it-s-original-core-was-completely-changed" tabindex="-1"><a class="header-anchor" href="#it-s-believed-that-one-such-planet-was-10-times-the-mass-of-earth-and-it-was-mainly-a-silicate-ice-core-the-planet-hit-jupiter-with-an-impact-speed-of-46-km-s-jupiter-only-lost-a-small-amount-of-mass-from-the-collision-but-it-s-original-core-was-completely-changed" aria-hidden="true">#</a> It's believed that one such planet was 10 times the mass of Earth, and it was mainly a <code v-pre>silicate</code> ice core. The planet hit Jupiter with an impact speed of 46 km/s. Jupiter only lost a small amount of mass from the collision, but it's original core was completely changed.</h4>
<p>可以确定的是其中一颗行星的质量是地球的10倍，核心主要是硅酸盐。这颗行星以46公里/秒的速度撞击木星。在这次碰撞中，木星只损失了少量的质量，但它原来的核心完全改变了。</p>
<h4 id="before-the-impact-jupiter-had-a-dense-central-core-of-heavy-elements-and-the-rest-of-the-planet-was-made-up-of-hydrogen-and-helium-after-the-impact-the-infant-planet-s-silicate-ice-core-merged-with-jupiter-s-causing-jupiter-s-core-to-become-diluted-the-heavy-elements-spread-out-and-mixed-with-the-outer-layers-of-jupiter" tabindex="-1"><a class="header-anchor" href="#before-the-impact-jupiter-had-a-dense-central-core-of-heavy-elements-and-the-rest-of-the-planet-was-made-up-of-hydrogen-and-helium-after-the-impact-the-infant-planet-s-silicate-ice-core-merged-with-jupiter-s-causing-jupiter-s-core-to-become-diluted-the-heavy-elements-spread-out-and-mixed-with-the-outer-layers-of-jupiter" aria-hidden="true">#</a> Before the impact, Jupiter had a <code v-pre>dense</code> central core of heavy elements, and the rest of the planet was made up of <code v-pre>hydrogen</code> and <code v-pre>helium</code>. After the impact, the infant planet's silicate ice core merged with Jupiter's, causing Jupiter's core to become <code v-pre>diluted</code>. The heavy elements spread out and mixed with the outer layers of Jupiter.</h4>
<p>在撞击之前，木星有一个高密度的重元素核心，行星其他部分是由氢和氦组成。撞击之后，这颗幼年行星的硅酸盐冰核与木星的核心合并，导致木星核心被稀释。重元素向外扩散并于木星的外层混合。</p>
<h4 id="while-this-collision-was-a-defining-moment-for-jupiter-it-meant-the-end-of-the-road-for-the-other-planet-so-what-are-the-odds-that-earth-s-fate-would-be-any-different-well-let-s-find-out" tabindex="-1"><a class="header-anchor" href="#while-this-collision-was-a-defining-moment-for-jupiter-it-meant-the-end-of-the-road-for-the-other-planet-so-what-are-the-odds-that-earth-s-fate-would-be-any-different-well-let-s-find-out" aria-hidden="true">#</a> While this collision was a defining moment for Jupiter, it meant the end of the road for the other planet. So what are the odds that Earth's fate would be any different? Well, let's find out.</h4>
<p>虽然这次撞击对木星来说是一个决定性的时刻，但它也意味着另一个行星道路的终结。那么地球的命运会有什么不同呢，让我们来看看。</p>
<h4 id="the-earth-orbits-around-the-sun-at-an-average-velocity-of-29-78-km-s-at-this-speed-if-the-earth-were-to-just-leave-its-orbit-around-the-sun-and-head-straight-for-jupiter-it-would-take-about-242-days-to-get-there-throughout-our-journey-jupiter-would-shine-like-a-bright-star-growing-bigger-day-by-day-hour-by-hour" tabindex="-1"><a class="header-anchor" href="#the-earth-orbits-around-the-sun-at-an-average-velocity-of-29-78-km-s-at-this-speed-if-the-earth-were-to-just-leave-its-orbit-around-the-sun-and-head-straight-for-jupiter-it-would-take-about-242-days-to-get-there-throughout-our-journey-jupiter-would-shine-like-a-bright-star-growing-bigger-day-by-day-hour-by-hour" aria-hidden="true">#</a> The Earth orbits around the Sun at an average <code v-pre>velocity</code> of 29.78 km/s. At this speed, if the Earth were to just leave its orbit around the Sun and head straight for Jupiter, it would take about 242 days to get there. Throughout our journey, Jupiter would shine like a bright star, growing bigger day by day, hour by hour.</h4>
<p>地球绕太阳公转的平均速度是29.78公里/秒。如果地球以这样的速度离开围绕太阳运行的轨道直奔木星而去，大约需要242天的时间。在我们的旅程中，木星会像一颗明亮的恒星一样发光，一天比一天大，甚至每小时都不同。</p>
<h4 id="by-day-6-jupiter-would-appear-as-bright-as-our-moon-soon-we-would-to-notice-our-daylight-becoming-dimmer-we-ll-only-get-about-50-percent-of-our-normal-sunlight-when-we-reach-mars-s-orbit-luckily-for-us-the-earth-s-atmosphere-would-act-as-a-buffer-so-we-wouldn-t-experience-the-cold-right-away-but-that-will-only-last-a-while-so-you-ll-need-to-invest-in-some-heavy-duty-winter-gear-to-put-it-in-perspective-mars-has-a-surface-temperature-of-63°c-so-that-s-basically-what-we-d-have-to-look-forward-to" tabindex="-1"><a class="header-anchor" href="#by-day-6-jupiter-would-appear-as-bright-as-our-moon-soon-we-would-to-notice-our-daylight-becoming-dimmer-we-ll-only-get-about-50-percent-of-our-normal-sunlight-when-we-reach-mars-s-orbit-luckily-for-us-the-earth-s-atmosphere-would-act-as-a-buffer-so-we-wouldn-t-experience-the-cold-right-away-but-that-will-only-last-a-while-so-you-ll-need-to-invest-in-some-heavy-duty-winter-gear-to-put-it-in-perspective-mars-has-a-surface-temperature-of-63°c-so-that-s-basically-what-we-d-have-to-look-forward-to" aria-hidden="true">#</a> By day 6, Jupiter would appear as bright as our moon. Soon we would to notice our daylight becoming dimmer. We'll only get about 50 percent of our normal sunlight when we reach Mars's orbit. Luckily for us, the earth's atmosphere would act as a buffer, so we wouldn't experience the cold right away. But that will only last a while, so you'll need to invest in some heavy-duty winter gear. To put it in perspective, Mars has a surface temperature of -63℃, so that's basically what we'd have to look forward to.</h4>
<p>到第六天，木星就会像我们的月亮一样明亮，不久我们就会意识到白天会越来越暗淡。当我们到达火星轨道时，我们只能获得正常阳光的50%。幸运的是，地球的大气层将起到缓冲的作用，所以我们不会立马感受到寒冷。但这是能持续一段时间，所以你需要准备一些重型的防寒装备。更准确的说，火星的表面温度是-63℃，所以这基本上就是我们所要面对的。</p>
<h4 id="once-we-speed-through-mars-s-orbit-we-ll-pass-through-the-asteroid-belt-we-ll-get-to-see-beautiful-meteor-showers-lighting-up-the-sky-but-we-ll-also-be-at-risk-with-colliding-with-some-of-those-meteors-so-let-s-keep-moving" tabindex="-1"><a class="header-anchor" href="#once-we-speed-through-mars-s-orbit-we-ll-pass-through-the-asteroid-belt-we-ll-get-to-see-beautiful-meteor-showers-lighting-up-the-sky-but-we-ll-also-be-at-risk-with-colliding-with-some-of-those-meteors-so-let-s-keep-moving" aria-hidden="true">#</a> Once we speed through Mars's orbit, we'll pass through the asteroid belt. We'll get to see beautiful <code v-pre>meteor</code> showers lighting up the sky, but we'll also be at risk with colliding with some of those meteors, so let's keep moving.</h4>
<p>一旦我们快速穿过火星轨道，我们就要穿过小行星带。我们将看到美丽的流星雨照亮天空，但我们也会面临与一些流行相撞的风险。让我们继续前进。</p>
<h4 id="after-242-days-of-traveling-through-our-solar-system-we-would-finally-reach-our-destination-jupiter-as-the-earth-is-pulled-into-jupiter-our-planet-s-velocity-could-increase-until-it-reaches-60-km-s-that-s-250-times-faster-than-an-airplane-flies-so-you-ll-want-to-hold-on-tight-oh-and-did-we-mention-that-jupiter-has-79-confirmed-moons-orbiting-it-at-all-times-so-there-s-a-serious-risk-that-we-could-collide-with-any-of-them-as-the-earth-is-pulled-in-closer-and-if-we-do-happen-to-avoid-all-those-moons-things-will-only-get-worse" tabindex="-1"><a class="header-anchor" href="#after-242-days-of-traveling-through-our-solar-system-we-would-finally-reach-our-destination-jupiter-as-the-earth-is-pulled-into-jupiter-our-planet-s-velocity-could-increase-until-it-reaches-60-km-s-that-s-250-times-faster-than-an-airplane-flies-so-you-ll-want-to-hold-on-tight-oh-and-did-we-mention-that-jupiter-has-79-confirmed-moons-orbiting-it-at-all-times-so-there-s-a-serious-risk-that-we-could-collide-with-any-of-them-as-the-earth-is-pulled-in-closer-and-if-we-do-happen-to-avoid-all-those-moons-things-will-only-get-worse" aria-hidden="true">#</a> After 242 days of traveling through our Solar System, we would finally reach our destination: Jupiter. As the Earth is pulled into Jupiter, our planet's velocity could increase until it reaches 60 km/s. That's 250 times faster than an airplane flies, so you'll want to hold on tight. Oh, and did we mention that Jupiter has 79 confirmed moons orbiting it at all times? So there's a serious risk that we could collide with any of them as the Earth is pulled in closer. And if we do happen to avoid all those moons, things will only get worse.</h4>
<p>在太阳系穿梭了242天后，我们终于到达了目的地：木星。当地球被拉入木星时，速度可能会增加至60km/s。这比飞机速度块250倍，所以你要抓紧了。对了，我们提到过木星有79颗卫星一直围绕着它转吗？所以当地球被拉得更近时，我们很可能与它们中得任何一个发生碰撞。如果我们碰巧避开了所有这些卫星，情况指挥变得更糟。</p>
<h4 id="as-we-crash-into-jupiter-both-planets-atmospheres-will-be-compressed-rapidly-increasing-the-temperature-and-essentially-setting-the-air-on-fire-but-at-least-we-won-t-have-to-worry-about-colliding-with-jupiter-s-core-because-we-ll-never-make-it-there-our-planet-is-too-small-and-would-burn-up-in-the-atmosphere-before-that-ever-happens-but-this-would-have-a-huge-impact-on-jupiter-as-the-earth-s-remains-would-completely-mix-into-it-s-atmosphere" tabindex="-1"><a class="header-anchor" href="#as-we-crash-into-jupiter-both-planets-atmospheres-will-be-compressed-rapidly-increasing-the-temperature-and-essentially-setting-the-air-on-fire-but-at-least-we-won-t-have-to-worry-about-colliding-with-jupiter-s-core-because-we-ll-never-make-it-there-our-planet-is-too-small-and-would-burn-up-in-the-atmosphere-before-that-ever-happens-but-this-would-have-a-huge-impact-on-jupiter-as-the-earth-s-remains-would-completely-mix-into-it-s-atmosphere" aria-hidden="true">#</a> As we crash into Jupiter, both planets' atmospheres will be <code v-pre>compressed</code>, rapidly increasing the temperature, and essentially setting the air on fire. But at least we won't have to worry about colliding with Jupiter's core, because we'll never make it there. Our planet is too small and would burn up in the atmosphere before that ever happens. But this would have a huge impact on Jupiter, as the Earth's remains would completely mix into it's atmosphere.</h4>
<p>当我们撞向木星时，这两个行星的大气层都会被压缩，温度会迅速升高，甚至会让空气着火。但至少我们不用担心撞到木星的核心，因为我们不可能到那里。我们的星球太小了，在这种情况发生前就会被烧毁在大气层中。但这将会对木星产生影响，因为地球的残骸将会完全混合到它的大气层中。</p>
<h4 id="so-if-you-ever-notice-our-planet-going-off-course-and-heading-towards-jupiter-you-might-want-to-jump-off-along-the-way-maybe-right-as-we-pass-over-mars" tabindex="-1"><a class="header-anchor" href="#so-if-you-ever-notice-our-planet-going-off-course-and-heading-towards-jupiter-you-might-want-to-jump-off-along-the-way-maybe-right-as-we-pass-over-mars" aria-hidden="true">#</a> So if you ever notice our planet going off course and heading towards Jupiter, you might want to jump off along the way. Maybe right as we pass over Mars.</h4>
<p>所以，如果你注意到我们的星球偏离了轨道，朝着木星飞去，你可能想要中途跳下，也许就在我们飞过火星的时候。</p>
<src-rtyAudio :src="`https://rtyxmd.gitee.io/rtyresources2020/November/What%20If%20Jupiter%20Swallowed%20Earth.mp3`"></src-rtyAudio></div></template>
