<template><div><h1 id="不拿自己和别人比较" tabindex="-1"><a class="header-anchor" href="#不拿自己和别人比较" aria-hidden="true">#</a> 不拿自己和别人比较</h1>
<h3 id="stop-comparing-yourself-to-others" tabindex="-1"><a class="header-anchor" href="#stop-comparing-yourself-to-others" aria-hidden="true">#</a> Stop comparing yourself to others</h3>
<h2 id="翻译" tabindex="-1"><a class="header-anchor" href="#翻译" aria-hidden="true">#</a> 翻译</h2>
<h4 id="it-seems-we-have-been-measured-almost-all-of-our-lives-when-we-are-infants-with-our-height-and-our-weight-and-as-we-grew-it-became-our-speed-and-our-strength-and-even-in-school-there-are-test-scores-and-today-with-our-salarries-and-job-performance-it-seems-as-if-those-personal-averages-are-almost-always-used-to-measure-where-we-are-in-comparison-to-our-peers" tabindex="-1"><a class="header-anchor" href="#it-seems-we-have-been-measured-almost-all-of-our-lives-when-we-are-infants-with-our-height-and-our-weight-and-as-we-grew-it-became-our-speed-and-our-strength-and-even-in-school-there-are-test-scores-and-today-with-our-salarries-and-job-performance-it-seems-as-if-those-personal-averages-are-almost-always-used-to-measure-where-we-are-in-comparison-to-our-peers" aria-hidden="true">#</a> It seems we have been measured almost all of our lives, when we are infants, with our height and our weight, and as we grew it became our speed and our strength. And even in school there are test scores and today with our salarries and job performance. It seems as if those personal averages are almost always used to measure where we are in comparison to our peers.</h4>
<p>我们的一生似乎都在被不同的指标来测量，在婴儿时期，就量身高和体重，而长大后，是速度和耐力。甚至在学校，也有测试分数，如今，则是我们的薪水和工作表现。似乎这些个人的平均数值总是被拿来与身边人的水平作比较。</p>
<h4 id="and-i-think-we-should-look-at-that-a-little-differently-that-personal-average-is-just-that-it-s-something-very-personal-and-it-s-for-you-and-i-think-if-you-focus-on-that-and-work-to-build-that-you-can-really-start-to-accomplish-some-really-amazing-things" tabindex="-1"><a class="header-anchor" href="#and-i-think-we-should-look-at-that-a-little-differently-that-personal-average-is-just-that-it-s-something-very-personal-and-it-s-for-you-and-i-think-if-you-focus-on-that-and-work-to-build-that-you-can-really-start-to-accomplish-some-really-amazing-things" aria-hidden="true">#</a> And I think we should look at that a little differently. That personal average is just that, it's something very personal and it's for you, and I think if you focus on that and work to build that, you can really start to accomplish some really amazing things.</h4>
<p>但我认为我们应该用略微不同的方式来看待它。个人平均值是非常私人的，是你的专属，我认为如果你专注于个人水平方面，并在此基础上努力提升自己，你真的会开始取得很多令人惊讶的成就。</p>
<h4 id="this-idea-started-for-me-on-december-evening-in-2011-i-has-just-stepped-outside-to-do-our-evening-chores-to-feed-our-horses-i-hopped-into-our-tractor-and-a-few-minutes-later-a-five-foot-tall-700-pound-bale-of-hay-fell-from-the-loader-crushing-me-in-the-seat-of-the-tractor-and-in-the-process-shattering-my-t5-and-t6-vertebrae" tabindex="-1"><a class="header-anchor" href="#this-idea-started-for-me-on-december-evening-in-2011-i-has-just-stepped-outside-to-do-our-evening-chores-to-feed-our-horses-i-hopped-into-our-tractor-and-a-few-minutes-later-a-five-foot-tall-700-pound-bale-of-hay-fell-from-the-loader-crushing-me-in-the-seat-of-the-tractor-and-in-the-process-shattering-my-t5-and-t6-vertebrae" aria-hidden="true">#</a> This idea started for me on December evening in 2011. I has just stepped outside to do our evening <code v-pre>chores</code> to feed our horses. I hopped into our tractor and a few minutes later, a five foot tall, 700-pound bale of hay fell from the loader, crushing me in the seat of the tractor, and in the process <code v-pre>shattering</code> my T5 and T6 <code v-pre>vertebrae</code>.</h4>
<p>2011年12月的一个晚上，我有了这一想法。我刚准备出去做一些晚间的家务，喂马。我跳上我家的拖拉机，几分钟后，一捆1.5米高，350公斤重的干草从拖拉机的装载架上倒下来，砸到了坐在拖拉机上的我，这一下子碾碎了我第五和第六节胸椎。</p>
<h4 id="i-didn-t-lose-consciousness-but-i-felt-this-buzz-throughout-my-body-and-i-knew-what-had-happened-right-away-my-hands-were-reaching-for-my-legs-but-my-legs-didn-t-recognize-anything-touching-them-and-in-fact-i-couldn-t-feel-anything-from-the-center-of-my-chest-down" tabindex="-1"><a class="header-anchor" href="#i-didn-t-lose-consciousness-but-i-felt-this-buzz-throughout-my-body-and-i-knew-what-had-happened-right-away-my-hands-were-reaching-for-my-legs-but-my-legs-didn-t-recognize-anything-touching-them-and-in-fact-i-couldn-t-feel-anything-from-the-center-of-my-chest-down" aria-hidden="true">#</a> I didn't lose consciousness, but I felt this buzz throughout my body, and I knew what had happened right away. My hands were reaching for my legs, but my legs didn't recognize anything touching them. And in fact, I couldn't feel anything from the center of my chest down.</h4>
<p>我没有失去意识，但我感到一股酥麻传遍全身，我立马就知道发生了什么。我把收伸向我的腿，但我的腿没有任何知觉。实际上，我胸部以下都没有了任何知觉。</p>
<h4 id="so-there-i-was-about-100-feet-from-the-house-with-my-arms-wrapped-around-the-steering-the-wheel-trying-to-hold-myself-up-waiting-for-help-and-unlike-what-you-see-in-tv-and-the-movies-as-much-as-i-tried-to-get-the-dogs-to-go-to-the-house-and-get-help-they-just-stared-at-me" tabindex="-1"><a class="header-anchor" href="#so-there-i-was-about-100-feet-from-the-house-with-my-arms-wrapped-around-the-steering-the-wheel-trying-to-hold-myself-up-waiting-for-help-and-unlike-what-you-see-in-tv-and-the-movies-as-much-as-i-tried-to-get-the-dogs-to-go-to-the-house-and-get-help-they-just-stared-at-me" aria-hidden="true">#</a> So there I was, about 100 feet from the house, with my arms wrapped around the <code v-pre>steering</code> the wheel, trying to hold myself up, waiting for help. And unlike what you see in TV and the movies, as much as I tried to get the dogs to go to the house and get help -- they just stared at me.</h4>
<p>当时，我离家还有30米远，双手抱着方向盘，尝试着将自己支撑起来，等待救援。与你在电视和电影中看到的不同，我尝试着让狗跑回家帮我求助--可是它们只是在那里盯着我看。</p>
<h4 id="well-45-minutes-later-my-wife-came-home-and-i-heard-her-step-out-of-the-house-and-like-normal-if-i-needed-help-hey-do-you-need-help-and-i-said-yes-and-there-was-a-brief-pause-and-then-i-heard-her-yell-do-you-need-911-help-and-again-i-yelled-yes-well-not-long-after-i-was-enjoying-my-very-first-helicopter-ride-all-the-way-to-the-hospital" tabindex="-1"><a class="header-anchor" href="#well-45-minutes-later-my-wife-came-home-and-i-heard-her-step-out-of-the-house-and-like-normal-if-i-needed-help-hey-do-you-need-help-and-i-said-yes-and-there-was-a-brief-pause-and-then-i-heard-her-yell-do-you-need-911-help-and-again-i-yelled-yes-well-not-long-after-i-was-enjoying-my-very-first-helicopter-ride-all-the-way-to-the-hospital" aria-hidden="true">#</a> Well, 45 minutes later, my wife came home, and I heard her step out of the house, and like normal, if I needed help, &quot;Hey, do you need help?&quot; And I said, &quot;Yes.&quot; And there was a brief pause and then I heard her yell, &quot;Do you need 911 help?&quot; And again I yelled, &quot;Yes.&quot; Well, not long after I was enjoying my very first helicopter ride, all the way to the hospital.</h4>
<p>45分钟后，我的妻子回家了，我听到她走出房子，就和往常一样看我是否需要帮助，“嘿，需要我帮忙吗？”然后我说：“要。”短暂停顿后，我听到她大喊：“你需要我打911急救吗？”我再次喊道：“要。”很快，我就享受了第一次坐直升机的经历，一路直达医院。</p>
<h4 id="now-the-injury-wasn-t-very-dramatic-or-graphic-i-simply-broke-a-bone-or-two-and-in-the-process-i-was-told-i-d-probably-never-walk-again-it-became-very-normal-for-me-to-use-a-rope-to-sit-up-in-bed-because-my-abdominal-muscles-no-longer-work-or-to-use-a-board-to-slide-out-of-bed-into-a-wheelchair-or-to-even-wait-for-people-to-reach-things-for-me" tabindex="-1"><a class="header-anchor" href="#now-the-injury-wasn-t-very-dramatic-or-graphic-i-simply-broke-a-bone-or-two-and-in-the-process-i-was-told-i-d-probably-never-walk-again-it-became-very-normal-for-me-to-use-a-rope-to-sit-up-in-bed-because-my-abdominal-muscles-no-longer-work-or-to-use-a-board-to-slide-out-of-bed-into-a-wheelchair-or-to-even-wait-for-people-to-reach-things-for-me" aria-hidden="true">#</a> Now, the injury wasn't very dramatic or <code v-pre>graphic</code>. I simply broke a bone or two. And in the process, I was told I'd probably never walk again. It became very normal for me to use a rope to sit up in bed, because my <code v-pre>abdominal</code> muscles no longer work. Or to use a board to slide out of bed into a wheelchair, or to even wait for people to reach things for me.</h4>
<p>我的伤势并没有想象中那么严重。我只是断了一两根骨头。救治过程中，医生却告诉我，我可能这辈子再也无法走路了。借助一根绳子从床上坐起来对我来说成为了日常，因为我的腹部肌肉不再起作用了。我也习惯用一块板子从床上滑到轮椅，或者甚至是等着别人帮我拿东西。</p>
<h4 id="everything-that-i-had-learned-and-had-known-about-my-height-and-my-strength-and-my-balance-and-my-mobility-was-blown-away-my-entire-personal-average-had-been-reset" tabindex="-1"><a class="header-anchor" href="#everything-that-i-had-learned-and-had-known-about-my-height-and-my-strength-and-my-balance-and-my-mobility-was-blown-away-my-entire-personal-average-had-been-reset" aria-hidden="true">#</a> Everything that I had learned and had known about my height and my strength and my balance and my mobility was blown away. My entire personal average had been reset.</h4>
<p>我曾学到的以及知晓的，关于自己的身高、力量、平衡力以及运动能力的一切都不复存在。我的全部个人平均值都归零了。</p>
<h4 id="now-you-could-be-sure-in-those-days-i-was-being-measured-more-than-ever-by-the-doctors-and-nurses-for-sure-but-maybe-more-so-in-my-own-mind-and-i-found-myself-camparing-what-i-thought-i-was-going-to-be-able-to-do-going-forward-with-what-i-once-was-able-to-do-and-i-became-pretty-frustrated-it-took-some-very-consistent-prodding-from-my-wife-who-kept-saying-get-your-eyes-up-before-i-could-get-moving-forward" tabindex="-1"><a class="header-anchor" href="#now-you-could-be-sure-in-those-days-i-was-being-measured-more-than-ever-by-the-doctors-and-nurses-for-sure-but-maybe-more-so-in-my-own-mind-and-i-found-myself-camparing-what-i-thought-i-was-going-to-be-able-to-do-going-forward-with-what-i-once-was-able-to-do-and-i-became-pretty-frustrated-it-took-some-very-consistent-prodding-from-my-wife-who-kept-saying-get-your-eyes-up-before-i-could-get-moving-forward" aria-hidden="true">#</a> Now you could be sure in those days I was being measured more than ever, by the doctors and nurses for sure but maybe more so in my own mind, and I found myself camparing what I thought I was going to be able to do going forward with what I once was able to do. And I became pretty frustrated. It took some very consistent <code v-pre>prodding</code> from my wife, who kept saying, &quot;Get your eyes up,&quot; before I could get moving forward.</h4>
<p>毫无疑问，在那些日子里，我被测量的次数多的数不胜数，会经常被医生和护士测量，但可能更多的是在我的脑海里，我发现自己在比较从此之后自己能做到的事，和我曾经能做到的事。因此我变得非常挫败。我的妻子一直在对我说“抬起头来”，在她坚持不懈的鼓励下，我才开始了继续前行。</p>
<h4 id="and-i-soon-realized-that-almost-had-to-forget-about-the-person-i-was-before-and-the-things-i-was-able-to-do-before-i-almost-had-to-pretend-it-was-never-me-and-i-m-afraid-if-i-had-not-made-that-realization-my-frustration-would-have-turned-into-something-much-harder-to-recover-from" tabindex="-1"><a class="header-anchor" href="#and-i-soon-realized-that-almost-had-to-forget-about-the-person-i-was-before-and-the-things-i-was-able-to-do-before-i-almost-had-to-pretend-it-was-never-me-and-i-m-afraid-if-i-had-not-made-that-realization-my-frustration-would-have-turned-into-something-much-harder-to-recover-from" aria-hidden="true">#</a> And I soon realized that almost had to forget about the person I was before and the things I was able to do before. I almost had to pretend it was never me. And I'm afraid if I had not made that realization, my frustration would have turned into something much harder to recover from.</h4>
<p>很快，我意识到我几乎不得不忘记曾经的自己，忘记曾经我能做到的事。我几乎不得不假装曾经的那个人不是我。如果我当初没意识到这一点，恐怕我的挫败感会发展为其他更加难以康复的东西。</p>
<h4 id="now-luckily-a-few-weeks-later-i-was-transferred-to-a-specially-spinal-cord-rehab-hospital-about-10-hours-from-home-and-wouldn-t-you-know-the-first-day-of-rehab-and-the-first-session-we-had-something-called-fit-class-and-a-group-of-us-broke-into-teams-to-see-which-team-could-do-the-most-reps-in-the-weight-machine" tabindex="-1"><a class="header-anchor" href="#now-luckily-a-few-weeks-later-i-was-transferred-to-a-specially-spinal-cord-rehab-hospital-about-10-hours-from-home-and-wouldn-t-you-know-the-first-day-of-rehab-and-the-first-session-we-had-something-called-fit-class-and-a-group-of-us-broke-into-teams-to-see-which-team-could-do-the-most-reps-in-the-weight-machine" aria-hidden="true">#</a> Now, luckily, a few weeks later, I was transferred to a specially <code v-pre>spinal</code> cord <code v-pre>rehab</code> hospital about 10 hours from home, and wouldn't you know, the first day of rehab and the first session we had something called fit class, and a group of us broke into teams, to see which team could do the most reps in the weight machine.</h4>
<p>幸运的是，在几周后，我被转移到距离我家10小时车程的一家脊髓康复专科医院，你不会想到在康复训练的第一天，第一个环节，我们有一个所谓的“健身课”，我们一群人分成几组，看哪个小组能在举重器械上做最多次试举。</p>
<h4 id="now-we-ve-all-been-there-haven-t-been-to-the-gym-in-a-year-or-two-neither-had-i-and-so-what-do-you-do-you-try-to-do-what-you-did-a-couple-of-years-age-and-you-do-a-couple-of-sets-and-then-what-do-you-do-a-couple-more-and-you-re-felling-even-better-so-you-do-more-and-the-next-two-weeks-you-camplain-to-your-family-about-how-sore-you-are" tabindex="-1"><a class="header-anchor" href="#now-we-ve-all-been-there-haven-t-been-to-the-gym-in-a-year-or-two-neither-had-i-and-so-what-do-you-do-you-try-to-do-what-you-did-a-couple-of-years-age-and-you-do-a-couple-of-sets-and-then-what-do-you-do-a-couple-more-and-you-re-felling-even-better-so-you-do-more-and-the-next-two-weeks-you-camplain-to-your-family-about-how-sore-you-are" aria-hidden="true">#</a> Now, we've all been there, haven't been to the gym in a year or two. Neither had I. And so what do you do? You try to do what you did a couple of years age, and you do a couple of sets. And then what do you do? A couple more. And you're felling even better, so you do more. And the next two weeks you camplain to your family about how sore you are.</h4>
<p>我们都经历过一两年没去健身房的情况。我也是，那该怎么办？你尝试按照几年前的方式去做，你做了几组，之后呢？又做了几组。你感觉甚至更好了，于是你又多做了几组。在接下来的两周，你会和家人抱怨你的肌肉有多酸痛。</p>
<h4 id="well-my-team-went-all-out-and-we-won-we-won-big-and-for-the-next-three-days-i-could-not-straighten-my-arms-which-isn-t-that-big-a-deal-except-when-you-re-in-a-wheelchair-and-that-s-really-what-you-have-to-use-to-get-around" tabindex="-1"><a class="header-anchor" href="#well-my-team-went-all-out-and-we-won-we-won-big-and-for-the-next-three-days-i-could-not-straighten-my-arms-which-isn-t-that-big-a-deal-except-when-you-re-in-a-wheelchair-and-that-s-really-what-you-have-to-use-to-get-around" aria-hidden="true">#</a> Well, my team went all out and we won, we won big, and for the next three days I could not straighten my arms, which isn't that big a deal except when you're in a wheelchair, and that's really what you have to use to get around.</h4>
<p>我的小组全力以赴，大获全胜。但是在接下来的三天，我都没法伸直手臂，这听起来不是什么大事，除非你坐轮椅，你不得不用手臂操控轮椅到处走。</p>
<h4 id="and-that-proved-to-be-a-very-important-lesson-for-me-it-was-one-thing-that-i-couldn-t-compare-myself-to-myself-but-even-around-people-in-the-same-situation-in-that-hospital-i-found-that-i-couldn-t-try-to-keep-pace-or-set-pace-with-them-as-well-and-i-was-left-with-really-only-one-choiced-and-that-was-to-focus-on-who-i-was-at-that-point-in-time-with-there-i-needed-to-go-and-to-get-back-to-who-i-needed-to-be" tabindex="-1"><a class="header-anchor" href="#and-that-proved-to-be-a-very-important-lesson-for-me-it-was-one-thing-that-i-couldn-t-compare-myself-to-myself-but-even-around-people-in-the-same-situation-in-that-hospital-i-found-that-i-couldn-t-try-to-keep-pace-or-set-pace-with-them-as-well-and-i-was-left-with-really-only-one-choiced-and-that-was-to-focus-on-who-i-was-at-that-point-in-time-with-there-i-needed-to-go-and-to-get-back-to-who-i-needed-to-be" aria-hidden="true">#</a> And that proved to be a very important lesson for me. It was one thing that I couldn't compare myself to myself, but even around people in the same situation in that hospital, I found that I couldn't try to keep pace or set pace with them as well, and I was left with really only one choiced and that was to focus on who I was at that point in time, with there I needed to go and to get back to who I needed to be.</h4>
<p>这成为了我收获的一个很宝贵的教训--不能进行自我比较是一码事，但甚至是和同在那个医院、与我处境相同的人相比，我发现我也无法跟上他们的步伐，或是与他们并驾齐驱，于是我别无选择，只能专注于当下的自己，专注于我需要达成的目标，并且变回我需要成为的人。</p>
<h4 id="for-the-next-six-weeks-for-seven-to-eight-hours-a-day-that-s-what-i-did-i-built-little-by-little-and-as-you-might-expect-when-you-re-recovering-from-a-spinal-cord-injury-you-re-going-to-have-a-bad-day-you-might-have-a-few-in-a-row-what-i-found-out-is-that-good-and-bad-really-didn-t-have-a-lot-of-meaning-unless-i-had-the-context-of-knowing-what-my-average-was" tabindex="-1"><a class="header-anchor" href="#for-the-next-six-weeks-for-seven-to-eight-hours-a-day-that-s-what-i-did-i-built-little-by-little-and-as-you-might-expect-when-you-re-recovering-from-a-spinal-cord-injury-you-re-going-to-have-a-bad-day-you-might-have-a-few-in-a-row-what-i-found-out-is-that-good-and-bad-really-didn-t-have-a-lot-of-meaning-unless-i-had-the-context-of-knowing-what-my-average-was" aria-hidden="true">#</a> For the next six weeks, for seven to eight hours a day, that's what I did. I built little by little, and, as you might expect, when you're recovering from a spinal cord injury, you're going to have a bad day. You might have a few in a row. What I found out is that good and bad really didn't have a lot of meaning, unless I had the context of knowing what my average was.</h4>
<p>在接下来的六周，每天7-8小时，这就是我做的事，我一点一点努力，你可能也预料到，当你从脊髓损伤中恢复时，你将会度过很糟糕的一天。你可能连着几天都很糟糕。而我发现，好坏并没有什么重大的意义。除非我了解自己的平均值在哪里。</p>
<h4 id="it-was-really-up-to-me-to-decide-if-something-was-bad-or-good-based-on-where-i-was-at-that-point-in-time-and-it-was-in-my-control-to-determine-if-it-really-was-bad-day-in-fact-it-was-my-decision-on-whether-or-not-i-could-stop-a-streak-of-bad-days" tabindex="-1"><a class="header-anchor" href="#it-was-really-up-to-me-to-decide-if-something-was-bad-or-good-based-on-where-i-was-at-that-point-in-time-and-it-was-in-my-control-to-determine-if-it-really-was-bad-day-in-fact-it-was-my-decision-on-whether-or-not-i-could-stop-a-streak-of-bad-days" aria-hidden="true">#</a> It was really up to me to decide if something was bad or good, based on where I was at that point in time, and it was in my control to determine if it really was bad day. In fact, it was my decision on whether or not I could stop a streak of bad days.</h4>
<p>这完全取决于我自己，在那种时候什么是好，什么是坏。决定一天过得是否很糟糕完全在我的掌控范围内。实际上，我是否能停止一连串糟糕的日子也是我自己决定的。</p>
<h4 id="and-what-i-found-during-that-time-away-from-home-is-i-never-had-a-bad-day-even-with-everything-going-on-there-were-parts-of-my-day-that-certainly-not-as-pleasant-as-they-could-be-but-it-was-never-an-entirely-bad-day" tabindex="-1"><a class="header-anchor" href="#and-what-i-found-during-that-time-away-from-home-is-i-never-had-a-bad-day-even-with-everything-going-on-there-were-parts-of-my-day-that-certainly-not-as-pleasant-as-they-could-be-but-it-was-never-an-entirely-bad-day" aria-hidden="true">#</a> And what I found during that time away from home is I never had a bad day, even with everything going on. There were parts of my day that certainly not as pleasant as they could be, but it was never an entirely bad day.</h4>
<p>在离家的那段时间里，我发现即使发生各种事情，但没有一天是糟糕的。那些日子里，有的时候肯定不尽如人意，但那从来都不会是完全糟糕的一天。</p>
<h4 id="so-i-m-guessing-that-all-of-you-have-been-through-a-meeting-that-probably-didn-t-go-very-well-or-a-commute-that-wasn-t-as-great-as-you-would-like-it-or-even-burned-dinner-at-night-did-those-things-really-ruin-your-entire-day" tabindex="-1"><a class="header-anchor" href="#so-i-m-guessing-that-all-of-you-have-been-through-a-meeting-that-probably-didn-t-go-very-well-or-a-commute-that-wasn-t-as-great-as-you-would-like-it-or-even-burned-dinner-at-night-did-those-things-really-ruin-your-entire-day" aria-hidden="true">#</a> So I'm guessing that all of you have been through a meeting that probably didn't go very well, or a <code v-pre>commute</code> that wasn't as great as you would like it, or even burned dinner at night. Did those things really <code v-pre>ruin</code> your entire day?</h4>
<p>我猜你们所有人都经历过可能进行的不太顺利的会议，或不是很棒的通勤体验，甚至是烧焦了晚饭。这些小不幸真的会毁了你这一整天吗？</p>
<h4 id="what-i-found-in-those-scenarios-is-the-quicker-you-move-on-to-what-s-next-the-quicker-you-can-start-attacking-things-and-by-moving-on-to-next-as-fast-as-possible-you-shrink-the-time-you-spend-in-those-bad-scenarios-and-it-gives-more-time-for-the-good-and-as-a-result-the-good-outweight-the-bad-your-average-increases-and-that-s-just-how-the-math-works" tabindex="-1"><a class="header-anchor" href="#what-i-found-in-those-scenarios-is-the-quicker-you-move-on-to-what-s-next-the-quicker-you-can-start-attacking-things-and-by-moving-on-to-next-as-fast-as-possible-you-shrink-the-time-you-spend-in-those-bad-scenarios-and-it-gives-more-time-for-the-good-and-as-a-result-the-good-outweight-the-bad-your-average-increases-and-that-s-just-how-the-math-works" aria-hidden="true">#</a> What I found in those <code v-pre>scenarios</code> is the quicker you move on to what's next, the quicker you can start attacking things. And by moving on to next as fast as possible, you shrink the time you spend in those bad scenarios, and it gives more time for the good. And, as a result, the good outweight the bad, your average increases and that's just how the math works.</h4>
<p>在这些场景下，我发现，你越快将注意力转移到下一件事上，你就能更快的开始全力以赴。通过尽快把注意力转移到下一件事上，你缩减了在负面情景上所花费的时间，并把更多的时间专注于正面情景。因此，利大于弊，你的平均值也就提升了，这就是数学的原理。</p>
<h4 id="it-didn-t-matter-to-me-if-i-d-spent-the-morning-really-struggling-with-my-medication-or-at-lunch-my-legs-being-very-spastic-or-even-if-i-had-fallen-out-of-my-wheelchair-ask-my-wife-it-happens-quite-often-she-s-here-they-were-just-small-parts-of-my-day-and-small-parts-of-my-average" tabindex="-1"><a class="header-anchor" href="#it-didn-t-matter-to-me-if-i-d-spent-the-morning-really-struggling-with-my-medication-or-at-lunch-my-legs-being-very-spastic-or-even-if-i-had-fallen-out-of-my-wheelchair-ask-my-wife-it-happens-quite-often-she-s-here-they-were-just-small-parts-of-my-day-and-small-parts-of-my-average" aria-hidden="true">#</a> It didn't matter to me if I'd spent the morning really struggling with my medication, or at lunch my legs being very <code v-pre>spastic</code>, or even if I had fallen out of my wheelchair. Ask my wife, it happens quite often. She's here. They were just small parts of my day and small parts of my average.</h4>
<p>如果整个早上我都为吃药而苦苦挣扎，或在午饭时腿抽筋了，甚至从轮椅上摔下来，这些对我都不重要。可以问我妻子，这些经常发生。她就在这。但这些都是我一天中很小的一部分，我平均值中的一小部分。</p>
<h4 id="and-so-in-the-months-and-years-that-followed-i-continued-to-try-to-attack-things-in-that-way-and-before-i-knew-it-i-was-being-presented-with-some-pretty-incredible-challenges-like-completing-a-marathon-in-a-wheelchair" tabindex="-1"><a class="header-anchor" href="#and-so-in-the-months-and-years-that-followed-i-continued-to-try-to-attack-things-in-that-way-and-before-i-knew-it-i-was-being-presented-with-some-pretty-incredible-challenges-like-completing-a-marathon-in-a-wheelchair" aria-hidden="true">#</a> And so, in the months and years that followed, I continued to try to attack things in that way, and before I knew it I was being presented with some pretty incredible challenges, like completing a marathon in a wheelchair.</h4>
<p>于是，在后来的几个月以及几年中，我继续用这种方式全力以赴，而且在我意识到之前，我已经完成了不少令人难以置信的挑战，例如在轮椅上跑完一场马拉松。</p>
<h4 id="in-early-2016-i-met-my-physical-therapist-and-after-a-few-really-grueling-sessions-she-must-have-sensed-something-because-she-pulled-me-aside-and-said-you-know-you-should-do-a-half-marathon-in-your-wheelchair-and-oh-yeah-it-s-in-10-weeks" tabindex="-1"><a class="header-anchor" href="#in-early-2016-i-met-my-physical-therapist-and-after-a-few-really-grueling-sessions-she-must-have-sensed-something-because-she-pulled-me-aside-and-said-you-know-you-should-do-a-half-marathon-in-your-wheelchair-and-oh-yeah-it-s-in-10-weeks" aria-hidden="true">#</a> In early 2016, I met my physical <code v-pre>therapist</code>, and after a few really <code v-pre>grueling</code> sessions, she must have sensed something, because she pulled me aside and said, &quot;You know, you should do a half marathon. In your wheelchair. And, oh yeah, it's in 10 weeks.&quot;</h4>
<p>在2016年初，我见了我的理疗师，在几次非常艰苦的康复训练后，她一定感觉到了什么，因为她把我拉到一边说：“你应该参加半马。坐在轮椅上参加，哦，就在10周后。”</p>
<h4 id="and-i-thought-in-my-mind-you-re-crazy-i-didn-t-have-a-workout-plan-i-didn-t-have-any-way-of-knowing-how-fast-i-needed-to-go-or-how-far-i-was-supposed-to-go-but-i-simply-got-to-work-every-day-and-i-simply-wanted-to-be-as-good-as-or-as-fast-as-i-was-the-prior-day" tabindex="-1"><a class="header-anchor" href="#and-i-thought-in-my-mind-you-re-crazy-i-didn-t-have-a-workout-plan-i-didn-t-have-any-way-of-knowing-how-fast-i-needed-to-go-or-how-far-i-was-supposed-to-go-but-i-simply-got-to-work-every-day-and-i-simply-wanted-to-be-as-good-as-or-as-fast-as-i-was-the-prior-day" aria-hidden="true">#</a> And I thought in my mind, &quot;You're crazy.&quot; I didn't have a workout plan. I didn't have any way of knowing how fast I needed to go, or how far I was supposed to go. But I simply got to work, every day, and I simply wanted to be as good as or as fast as I was the <code v-pre>prior</code> day.</h4>
<p>我当时脑子里想：你太疯狂了，我没有锻炼计划，我也完全不知道我需要跑多快，或是我需要跑多远。但我还是开始锻炼，并开始每天记录和追踪每次健身，我只是简单想要让自己和之前的表现一样好、跑的一样快。</p>
<h4 id="and-in-the-end-i-really-created-that-average-for-myself-and-i-tried-to-build-on-that-as-much-as-i-could" tabindex="-1"><a class="header-anchor" href="#and-in-the-end-i-really-created-that-average-for-myself-and-i-tried-to-build-on-that-as-much-as-i-could" aria-hidden="true">#</a> And in the end I really created that average for myself, and I tried to build on that as much as I could.</h4>
<p>最后，我真的为自己创造了平均值，我也开始尽自己所能从那个数值开始更上一层楼。</p>
<h4 id="well-i-finished-that-race-right-in-time-with-what-my-average-should-have-been-and-somewhere-along-the-way-i-kind-of-closed-the-door-on-who-i-once-was-that-person-who-i-was-before-and-all-those-things-i-thought-i-was-able-to-do-really-didn-t-matter-in-fact-walking-again-really-didn-t-matter" tabindex="-1"><a class="header-anchor" href="#well-i-finished-that-race-right-in-time-with-what-my-average-should-have-been-and-somewhere-along-the-way-i-kind-of-closed-the-door-on-who-i-once-was-that-person-who-i-was-before-and-all-those-things-i-thought-i-was-able-to-do-really-didn-t-matter-in-fact-walking-again-really-didn-t-matter" aria-hidden="true">#</a> Well, I finished that race right in time with what my average should have been, and somewhere along the way, I kind of closed the door on who I once was. That person who I was before, and all those things I thought I was able to do really didn't matter. In fact. walking again really didn't matter.</h4>
<p>最后，我按时完成了比赛，速度也达到了我的平均水平，而且在途中，我似乎忘记了自己曾经的模样。那个事故发生前的我，以及自己曾经做到的一切，真的不那么重要了。实际上，能否重新走路真的不重要。</p>
<h4 id="it-became-much-less-of-a-goal-for-me-in-terms-of-where-i-was-going-to-go-and-besides-like-you-guys-are-so-slow-when-you-walk-in-crowds-like-this-it-is-so-difficult-i-m-like-get-out-of-the-way-we-re-going-places" tabindex="-1"><a class="header-anchor" href="#it-became-much-less-of-a-goal-for-me-in-terms-of-where-i-was-going-to-go-and-besides-like-you-guys-are-so-slow-when-you-walk-in-crowds-like-this-it-is-so-difficult-i-m-like-get-out-of-the-way-we-re-going-places" aria-hidden="true">#</a> It became much less of a goal for me in terms of where I was going to go. And besides, like, you guys are so slow when you walk. In crowds like this, it is so difficult. I'm like, &quot;Get out of the way, We're going places.&quot;</h4>
<p>就我想要达成的目标而言，走路已不再是那么重大的目标。而且，你们走路都超级慢。像在这样的人群中走路，太困难了。我会说：“借过，我们先走一步。”</p>
<h4 id="and-all-i-wanted-to-do-was-go-fast-so-i-did-what-i-thought-i-should-do-i-started-researching-wheelchair-racing-and-i-went-online-and-i-found-the-best-of-the-best-i-learned-their-technique-i-learned-about-the-equipment-and-i-was-lucky-to-have-a-coach-that-offered-me-a-way-to-get-started" tabindex="-1"><a class="header-anchor" href="#and-all-i-wanted-to-do-was-go-fast-so-i-did-what-i-thought-i-should-do-i-started-researching-wheelchair-racing-and-i-went-online-and-i-found-the-best-of-the-best-i-learned-their-technique-i-learned-about-the-equipment-and-i-was-lucky-to-have-a-coach-that-offered-me-a-way-to-get-started" aria-hidden="true">#</a> And all I wanted to do was go fast. So I did what I thought I should do. I started researching wheelchair racing. And I went online and I found the best of the best, I learned their technique, I learned about the equipment, and I was lucky to have a coach that offered me a way to get started.</h4>
<p>我一心只想变快，所以我就做了我认为自己该做的事。我开始研究轮椅竞速，我上网查，找到了一些最厉害的人，我学习他们的技术，研究装备的使用，我也很幸运有一个教练带我入门。</p>
<h4 id="and-after-talking-with-him-and-having-him-help-me-get-those-things-underway-as-i-was-leaving-he-says-you-know-you-should-do-the-2017-chicago-marathon-and-he-s-the-coach-i-can-t-tell-him-no" tabindex="-1"><a class="header-anchor" href="#and-after-talking-with-him-and-having-him-help-me-get-those-things-underway-as-i-was-leaving-he-says-you-know-you-should-do-the-2017-chicago-marathon-and-he-s-the-coach-i-can-t-tell-him-no" aria-hidden="true">#</a> And after talking with him, and having him help me get those things underway, as I was leaving, he says, &quot;You know, you should do the 2017 Chicago Marathon.&quot; And he's the coach, I can't tell him no.</h4>
<p>在和他聊完，让他帮我做好准备，正当我离开的时候，他说：“你应该参加2017芝加哥马拉松。”他是教练，我无法对他说不。</p>
<h4 id="so-with-that-guidance-i-went-back-home-and-i-got-to-work-much-like-in-the-prior-way-and-i-continued-researching-but-i-had-learned-my-lesson-i-was-really-carefull-not-to-compare-with-how-accomplished-those-people-on-the-internet-were-and-how-fast-they-were-because-if-i-had-i-probably-never-would-have-continued-going-through-with-it" tabindex="-1"><a class="header-anchor" href="#so-with-that-guidance-i-went-back-home-and-i-got-to-work-much-like-in-the-prior-way-and-i-continued-researching-but-i-had-learned-my-lesson-i-was-really-carefull-not-to-compare-with-how-accomplished-those-people-on-the-internet-were-and-how-fast-they-were-because-if-i-had-i-probably-never-would-have-continued-going-through-with-it" aria-hidden="true">#</a> So with that guidance, I went back home, and I got to work, much like in the prior way. And I continued researching but I had learned my lesson. I was really carefull not to compare with how accomplished those people on the internet were, and how fast they were, because if I had, I probably never would have continued going through with it.</h4>
<p>于是，在他的指导下，我回到家，继续像之前那样努力训练。我继续研究，但我已经得到教训，我非常小心，不把自己和网络上那些人的成就以及他们的速度进行比较，因为如果我这么做，我可能不会继续这场旅程并坚持至今。</p>
<h4 id="well-the-weekend-of-the-race-arrived-and-it-was-just-like-going-to-college-for-the-first-time-you-re-dumped-off-there-s-a-hole-bunch-of-people-around-you-you-don-t-really-know-very-many-of-them-somebody-s-got-the-cool-stereo-and-the-cool-tv-and-they-re-smart-and-they-re-pretty-and-they-re-cute-and-they-re-handsome-and-you-don-t-know-if-you-really-belong" tabindex="-1"><a class="header-anchor" href="#well-the-weekend-of-the-race-arrived-and-it-was-just-like-going-to-college-for-the-first-time-you-re-dumped-off-there-s-a-hole-bunch-of-people-around-you-you-don-t-really-know-very-many-of-them-somebody-s-got-the-cool-stereo-and-the-cool-tv-and-they-re-smart-and-they-re-pretty-and-they-re-cute-and-they-re-handsome-and-you-don-t-know-if-you-really-belong" aria-hidden="true">#</a> Well, the weekend of the race arrived, and it was just like going to college for the first time. You're dumped off, there's a hole bunch of people around you, you don't really know very many of them, somebody's got the cool <code v-pre>stereo</code> and the cool TV, and they're smart and they're pretty and they're cute and they're handsome, and you don't know if you really belong.</h4>
<p>举行比赛的周末到了，这就好像第一次上大学，你独自被抛下，周围有一群人，但其中没几个你认识的人。有人带着酷炫的音响或电视，他们看起来聪明、漂亮、可爱、帅气，你不确定自己是否真的属于这里。</p>
<h4 id="but-then-somebody-says-hey-let-s-go-get-food-and-all-of-a-sudden-that-friend-group-happens-and-you-start-to-settle-in" tabindex="-1"><a class="header-anchor" href="#but-then-somebody-says-hey-let-s-go-get-food-and-all-of-a-sudden-that-friend-group-happens-and-you-start-to-settle-in" aria-hidden="true">#</a> But then somebody says, &quot;Hey, let's go get food.&quot; And all of a sudden, that friend group happens, and you start to settle in.</h4>
<p>但这是有人会说：“嘿，我们去吃点东西。”突如其来的朋友圈形成了，你也开始适应。</p>
<h4 id="well-that-weekend-of-the-race-we-had-a-meeting-called-the-wheelchairs-meeting-and-there-were-60-wheelchairs-in-that-room-the-night-before-the-race-and-wouldn-t-you-know-it-all-of-the-people-that-i-had-been-researching-were-there-the-best-in-the-world" tabindex="-1"><a class="header-anchor" href="#well-that-weekend-of-the-race-we-had-a-meeting-called-the-wheelchairs-meeting-and-there-were-60-wheelchairs-in-that-room-the-night-before-the-race-and-wouldn-t-you-know-it-all-of-the-people-that-i-had-been-researching-were-there-the-best-in-the-world" aria-hidden="true">#</a> Well, that weekend of the race, we had a meeting called the Wheelchairs Meeting, and there were 60 wheelchairs in that room the night before the race. And wouldn't you know it, all of the people that I had been researching were there, the best in the world.</h4>
<p>那个比赛的周末，在比赛前的那晚，我们举办了一场“轮椅运动员聚会”，那个房间里总共有60个轮椅运动员。你不敢相信，那里的所有人，我都曾在网上搜索过他们，他们都是世界顶尖。</p>
<h4 id="there-must-have-been-over-50-paralympic-medals-in-the-room-that-day-and-i-felt-pretty-small-and-i-fell-back-into-that-trap-of-comparing-myself-i-knew-that-my-average-that-i-had-been-tracking-during-my-workouts-were-over-90-seconds-slower-per-mile-than-theirs" tabindex="-1"><a class="header-anchor" href="#there-must-have-been-over-50-paralympic-medals-in-the-room-that-day-and-i-felt-pretty-small-and-i-fell-back-into-that-trap-of-comparing-myself-i-knew-that-my-average-that-i-had-been-tracking-during-my-workouts-were-over-90-seconds-slower-per-mile-than-theirs" aria-hidden="true">#</a> There must have been over 50 Paralympic medals in the room that day. And I felt pretty small and I fell back into that trap of comparing myself. I knew that my average that I had been tracking during my workouts were over 90 seconds slower per mile than theirs.</h4>
<p>那天，那个房间里肯定有不止50枚残奥会奖牌。我感觉自己有些渺小，感觉自己再次陷入自我比较的陷阱中。我知道在自己所有的训练记录中，我每英里的平均用时要比他们慢90秒以上。</p>
<h4 id="and-the-coach-was-the-only-one-there-that-i-knew-and-he-reached-out-and-noticed-something-and-i-think-he-sensed-my-anxiety-and-he-invited-me-to-get-food-with-his-team-and-with-that-everything-settled-down-i-reallized-really-quick-that-they-didn-t-care-about-my-average-surely-and-i-had-forgotten-about-their" tabindex="-1"><a class="header-anchor" href="#and-the-coach-was-the-only-one-there-that-i-knew-and-he-reached-out-and-noticed-something-and-i-think-he-sensed-my-anxiety-and-he-invited-me-to-get-food-with-his-team-and-with-that-everything-settled-down-i-reallized-really-quick-that-they-didn-t-care-about-my-average-surely-and-i-had-forgotten-about-their" aria-hidden="true">#</a> And the coach was the only one there that I knew, and he reached out and noticed something, and I think he sensed my anxiety, and he invited me to get food with his team. And with that, everything settled down. I reallized really quick that they didn't care about my average, surely, and I had forgotten about their.</h4>
<p>教练是我在那里唯一认识的人，他过来和我讲话并注意到了什么，我觉得他感受到了我焦虑，因此他邀请我和他的团队一起吃饭。这一举动让一切安定下来，我很快意识到他们绝对不在意我的平均值，而且我也该忘记他们的成绩。</p>
<h4 id="well-that-next-day-i-finished-the-race-about-45-minutes-after-the-person-that-won-it-but-as-i-was-leaving-those-new-friends-who-are-very-close-today-challenged-me-to-stay-involved-and-to-keep-working-through-different-races-and-competitions-and-so-i-did-what-i-knew-how-i-went-home-and-i-got-busy" tabindex="-1"><a class="header-anchor" href="#well-that-next-day-i-finished-the-race-about-45-minutes-after-the-person-that-won-it-but-as-i-was-leaving-those-new-friends-who-are-very-close-today-challenged-me-to-stay-involved-and-to-keep-working-through-different-races-and-competitions-and-so-i-did-what-i-knew-how-i-went-home-and-i-got-busy" aria-hidden="true">#</a> Well that next day, I finished the race about 45 minutes after the person that won it. But as I was leaving, those new friends, who are very close today, challenged me to stay involved, and to keep working through different races and competitions. And so I did what I knew how. I went home, and I got busy.</h4>
<p>在第二天，我在获胜者冲线后约45分钟完成了比赛，但在我离开的时候，那些如今已非常亲近的新朋友，向我发起挑战，让我留在赛场上，完成一场又一场竞速和比赛。我就知道我该怎么做了，回家，开始忙于训练。</p>
<h4 id="now-as-you-can-imagine-being-in-a-wheelchair-let-alone-training-for-a-marathon-in-a-wheelchair-is-a-pretty-lonely-thing-i-have-an-incredible-group-of-friends-that-will-ride-bikes-with-me-and-keep-track-of-pace-and-help-me-out-but-in-the-end-it-s-still-five-to-six-days-a-week-it-s-50-to-69-miles-of-efforts-and-it-s-a-lot-of-alone-time" tabindex="-1"><a class="header-anchor" href="#now-as-you-can-imagine-being-in-a-wheelchair-let-alone-training-for-a-marathon-in-a-wheelchair-is-a-pretty-lonely-thing-i-have-an-incredible-group-of-friends-that-will-ride-bikes-with-me-and-keep-track-of-pace-and-help-me-out-but-in-the-end-it-s-still-five-to-six-days-a-week-it-s-50-to-69-miles-of-efforts-and-it-s-a-lot-of-alone-time" aria-hidden="true">#</a> Now, as you can imagine, being in a wheelchair, let alone training for a marathon in a wheelchair, is a pretty lonely thing. I have an incredible group of friends that will ride bikes with me and keep track of pace and help me out. But in the end, it's still five to six days a week, it's 50 to 69 miles of efforts, and it's a lot of alone time.</h4>
<p>你可以想象，在轮椅上，更别说在轮椅上为马拉松进行训练，是一件相当孤单的事。我又一群很棒的朋友，他们会骑车跟着我训练，检测我的节奏，帮助我。但到头来，依旧是一周五六天的训练，是50-60英里的努力，还有很多自我独处的时间。</p>
<h4 id="and-for-the-most-part-you-really-hove-nothing-to-rely-on-but-yourself-in-those-times-it-s-my-average-and-i-m-trying-to-get-better-little-by-little-well-this-fall-i-was-in-chicago-for-the-third-time-it-was-my-seventh-marathon-and-just-like-going-back-to-college-for-your-junior-years-you-re-anticipating-catching-up-with-friends-and-getting-excited-about-rolling-right-back-into-things" tabindex="-1"><a class="header-anchor" href="#and-for-the-most-part-you-really-hove-nothing-to-rely-on-but-yourself-in-those-times-it-s-my-average-and-i-m-trying-to-get-better-little-by-little-well-this-fall-i-was-in-chicago-for-the-third-time-it-was-my-seventh-marathon-and-just-like-going-back-to-college-for-your-junior-years-you-re-anticipating-catching-up-with-friends-and-getting-excited-about-rolling-right-back-into-things" aria-hidden="true">#</a> And for the most part, you really hove nothing to rely on but yourself in those times. It's my average, and I'm trying to get better little by little. Well, this fall I was in Chicago for the third time. It was my seventh marathon, and just like going back to college for your junior years, you're anticipating catching up with friends, and getting excited about rolling right back into things.</h4>
<p>绝大多数时间，你真的别无选择，只能靠自己。这是我的平均值，每天我都在尝试一点点变得更好。今年秋天是我第三次造访芝加哥，也是我的第七次马拉松，就好像大三时回学校一样，你期待和朋友重聚叙旧，对于立刻投入各种活动感到激动。</p>
<h4 id="well-i-attended-the-same-pre-race-meeting-and-the-same-pre-race-meal-and-caught-up-with-those-friends-and-we-lined-up-for-race-and-right-at-the-start-my-average-kicked-in-and-before-long-i-caught-up-with-some-of-those-friends-and-was-able-to-keep-pace-with-them-and-push-together-but-it-wasn-t-long-before-i-faded" tabindex="-1"><a class="header-anchor" href="#well-i-attended-the-same-pre-race-meeting-and-the-same-pre-race-meal-and-caught-up-with-those-friends-and-we-lined-up-for-race-and-right-at-the-start-my-average-kicked-in-and-before-long-i-caught-up-with-some-of-those-friends-and-was-able-to-keep-pace-with-them-and-push-together-but-it-wasn-t-long-before-i-faded" aria-hidden="true">#</a> Well, I attended the same pre-race meeting and the same pre-race meal, and caught up with those friends. And we lined up for race, and right at the start, my average kicked in, and before long I caught up with some of those friends, and was able to keep pace with them and push together. But it wasn't long before I faded.</h4>
<p>我照例会参加同样的赛前聚会和聚餐，和那些朋友们叙旧，但我们为比赛整装待发，在起点处，我的平均值猛然开始发挥作用，不久之后我就追赶上了那些朋友们，我们使用同样的步伐全速前进，一起挑战极限。但很快我又淡出了他们的视野。</p>
<h4 id="it-just-happened-and-i-found-myself-all-alone-again-with-really-nothing-to-rely-on-other-than-what-i-had-worked-so-hard-to-be-at-but-we-turned-into-wind-at-the-halfway-point-and-my-average-became-a-strong-advantage-and-it-wasn-t-long-before-i-caught-some-of-those-friends-and-passed-them-all-the-way-to-the-finish" tabindex="-1"><a class="header-anchor" href="#it-just-happened-and-i-found-myself-all-alone-again-with-really-nothing-to-rely-on-other-than-what-i-had-worked-so-hard-to-be-at-but-we-turned-into-wind-at-the-halfway-point-and-my-average-became-a-strong-advantage-and-it-wasn-t-long-before-i-caught-some-of-those-friends-and-passed-them-all-the-way-to-the-finish" aria-hidden="true">#</a> It just happened, and I found myself all alone again, with really nothing to rely on other than what I had worked so hard to be at. But we turned into wind at the halfway point, and my average became a strong advantage, and it wasn't long before I caught some of those friends, and passed them all the way to the finish.</h4>
<p>情况就这么发生，我发现自己又孤身一人，真的除了自己努力得来的东西，没什么能依靠的。但我们在半程遇上了逆风，我的平均值发挥了极大优势，很快我又追赶上了我的一些朋友，超过了他们，一路直奔终点。</p>
<h4 id="and-while-i-didn-t-set-a-personal-record-that-day-i-did-finish-30-seconds-per-mile-faster-than-my-prior-chicago-times-and-just-left-myself-pretty-excited" tabindex="-1"><a class="header-anchor" href="#and-while-i-didn-t-set-a-personal-record-that-day-i-did-finish-30-seconds-per-mile-faster-than-my-prior-chicago-times-and-just-left-myself-pretty-excited" aria-hidden="true">#</a> And while I didn't set a personal record that day, I did finish 30 seconds per mile faster than my prior Chicago times, and just left myself pretty excited.</h4>
<p>我尽管那天没有破自己的个人纪录，却比之前芝加哥的几次比赛每英里快了30秒。对此我还是蛮激动的。</p>
<h4 id="and-so-this-is-me-this-is-my-average-seventy-five-days-from-today-i-ll-be-in-bostom-for-my-second-time-i-m-super-excited-about-that-but-keep-in-mind-this-isn-t-really-just-about-racing-i-m-working-really-hard-every-day-to-be-better-in-so-many-other-ways-a-better-parent-a-better-husband-a-better-coach-teammate-friend-person-and-i-promise-you-even-though-what-you-see-here-is-very-visible-in-terms-of-challenges-that-i-face-everybody-here-has-something-that-they-re-fighting-and-it-may-be-visible-it-may-not-be-but-please-take-some-time-and-focus-on-you-instead-or-others-and-i-bet-you-can-win-those-challenges-and-really-start-accomplishing-so-many-great-things" tabindex="-1"><a class="header-anchor" href="#and-so-this-is-me-this-is-my-average-seventy-five-days-from-today-i-ll-be-in-bostom-for-my-second-time-i-m-super-excited-about-that-but-keep-in-mind-this-isn-t-really-just-about-racing-i-m-working-really-hard-every-day-to-be-better-in-so-many-other-ways-a-better-parent-a-better-husband-a-better-coach-teammate-friend-person-and-i-promise-you-even-though-what-you-see-here-is-very-visible-in-terms-of-challenges-that-i-face-everybody-here-has-something-that-they-re-fighting-and-it-may-be-visible-it-may-not-be-but-please-take-some-time-and-focus-on-you-instead-or-others-and-i-bet-you-can-win-those-challenges-and-really-start-accomplishing-so-many-great-things" aria-hidden="true">#</a> And so this is me. This is my average. Seventy-five days from today, I'll be in Bostom for my second time. I'm super excited about that. But keep in mind, this isn't really just about racing. I'm working really hard every day to be better in so many other ways, a better parent, a better husband, a better coach, teammate, friend, person. And I promise you, even though what you see here is very visible in terms of challenges that I face, everybody here has something that they're fighting, and it may be visible, it may not be, but please, take some time and focus on you instead or others, and I bet you can win those challenges, and really start accomplishing so many great things.</h4>
<p>这就是我，这就是我的平均值。75天之后，我将会第二次去波士顿。我为此非常兴奋。但记住，这不仅只是关于竞速。我每天都非常努力，力求在其他各个方面变好，成为更好的家长、更好的丈夫、更好的教练、队友、朋友、更好的人。我向你保证，即使你看到的我所面临的种种挑战，都非常显而易见，这里的每个人，都有在与之战斗的东西，有的肉眼可见、又可能不可见，但请花些时间、专注于自己，而非他人，我打赌你能战胜那些挑战，并真正地开始成就卓越。</p>
<h2 id="生词统计" tabindex="-1"><a class="header-anchor" href="#生词统计" aria-hidden="true">#</a> 生词统计</h2>
<table>
<thead>
<tr>
<th>单词</th>
<th>音标</th>
<th>翻译</th>
</tr>
</thead>
<tbody>
<tr>
<td>chore</td>
<td>tʃɔːr</td>
<td>n. 家庭杂物、日常零星事物</td>
</tr>
<tr>
<td>shatter</td>
<td>ˈʃætər</td>
<td>v. 粉碎、打碎、破坏； n. 碎片、乱七八糟的状态</td>
</tr>
<tr>
<td>vertebrae</td>
<td>ˈvɜːtɪbreɪ</td>
<td>n. 脊骨、脊椎</td>
</tr>
<tr>
<td>steer</td>
<td>stɪr</td>
<td>v. 控制、引导、驾驶</td>
</tr>
<tr>
<td>graphic</td>
<td>ˈɡræfɪk</td>
<td>adj. 形象的、图表的</td>
</tr>
<tr>
<td>abdominal</td>
<td>æbˈdɑːmɪnl</td>
<td>adj. 腹部的</td>
</tr>
<tr>
<td>prodding</td>
<td>ˈprɑːdɪŋ</td>
<td>n. 促进、刺激</td>
</tr>
<tr>
<td>spinal</td>
<td>ˈspaɪnl</td>
<td>adj. 脊髓的、脊柱的、脊骨的</td>
</tr>
<tr>
<td>rehab</td>
<td>ˈriːhæb</td>
<td>n. 康复治疗、修复之物； v. 恢复、康复、修缮</td>
</tr>
<tr>
<td>commute</td>
<td>kəˈmjuːt</td>
<td>n. 通勤； v. 通勤、代偿、减刑、交换</td>
</tr>
<tr>
<td>ruin</td>
<td>ˈruːɪn</td>
<td>n. 毁坏、毁灭、灭亡、破产、崩溃； v. 破坏、糟蹋、毁灭</td>
</tr>
<tr>
<td>scenario</td>
<td>səˈnærioʊ</td>
<td>n. 方案、情节、剧本、设想</td>
</tr>
<tr>
<td>spastic</td>
<td>ˈspæstɪk</td>
<td>adj. 痉挛的； n. 麻痹患者</td>
</tr>
<tr>
<td>therapist</td>
<td>ˈθerəpɪst</td>
<td>n. 治疗师、临床医学家</td>
</tr>
<tr>
<td>grueling</td>
<td>'ɡruəliŋ</td>
<td>adj. 使人精疲力尽的、艰辛的、让人受不了的</td>
</tr>
<tr>
<td>prior</td>
<td>ˈpraɪər</td>
<td>adj. 先前的、优先的</td>
</tr>
<tr>
<td>stereo</td>
<td>ˈsterioʊ</td>
<td>n. 立体声、立体声系统； adj. 立体的、立体声的</td>
</tr>
</tbody>
</table>
<h2 id="原文阅读" tabindex="-1"><a class="header-anchor" href="#原文阅读" aria-hidden="true">#</a> 原文阅读</h2>
<p>It seems we have been measured almost all of our lives, when we are infants, with our height and our weight, and as we grew it became our speed and our strength. And even in school there are test scores and today with our salaries and job performance. It seems as if those personal averages are almost always used to measure where we are in comparison to our peers.</p>
<p>And I think we should look at that a little differently. That personal average is just that, it's something very personal and it's for you, and I think if you focus on that and work to build that, you can really start to accomplish some really amazing things.</p>
<p>This idea started for me on a December evening in 2011. I has just stepped outside to do our evening chores to feed our horses. I hopped into our tractor and a few minutes later, a five foot tall, 700-pound bale of hay fell from the loader, crushing me in the seat of the tractor, and in the process shattering my T5 and T6 vertebrae.</p>
<p>I didn't lose consciousness, but I felt this buzz throughout my body, and I knew what had happened right away. My hands were reaching for my legs, but my legs didn't recognize anything touching them. And in fact, I couldn't feel anything from the center of my chest down.</p>
<p>So there I was, about 100 feet from the house, with my arms wrapped around the steering the wheel, trying to hold myself up, waiting for help. And unlike what you see in TV and the movies, as much as I tried to get the dogs to go to the house and get help -- they just stared at me.</p>
<p>Well, 45 minutes later, my wife came home, and I heard her step out of the house, and like normal, if I needed help, &quot;Hey, do you need help?&quot; And I said,&quot;Yes.&quot; And there was a brief pause and then I heard her yell, &quot;Do you need 911 help?&quot; And again I yelled, &quot;Yes.&quot; Well, not long after I was enjoying my very first helicopter ride, all the way to the hospital.</p>
<p>Now, the injury wasn't very dramatic or graphic. I simply broke a bone or two. And in the process, I was told I'd probably never walk again. It became very normal for me to use a rope to sit up in bed, because my abdominal muscles no longer work. Or to use a board to slide out of bed into a wheelchair, or to even wait for people to reach things for me.</p>
<p>Everything that I had learned and had known about my height and my strength and my balance and my mobility was blown away. My entire personal average had been reset.</p>
<p>Now you could be sure in those days I was being measured more than ever, by the doctors and nurses for sure but maybe more so in my own mind, and I found myself comparing what I thought I was going to be able to do going forward with what I once was able to do. And I became pretty frustrated. It took some very consistent prodding from my wife, who kept saying, &quot;Get your eyes up,&quot; before I could get moving forward.</p>
<p>And I soon realized that almost had to forget about the person I was before and the things I was able to do before. I almost had to pretend it was never me. And I'm afraid if I had not made that realization, my frustration would have turned into something much harder to recover from.</p>
<p>Now, luckily, a few weeks later, I was transferred to a specially spinal cord rehab hospital about 10 hours from home, and wouldn't you know, the first day of rehab and the first session we had something called fit class, and a group of us broke into teams, to see which team could do the most reps in the weight machine.</p>
<p>Now, we've all been there, haven't been to the gym in a year or two. Neither had I. And so what do you do? You try to do what you did a couple of years ago, and you do a couple of sets. And then what do you do? A couple more. And you're feeling even better, so you do more. And the next two weeks you complain to your family about how sore you are.</p>
<p>Well, my team went all out and we won, we won big, and for the next three days I could not straighten my arms, which isn't that big a deal except when you're in a wheelchair, and that's really what you have to use to get around.</p>
<p>And that proved to be a very important lesson for me. It was one thing that I couldn't compare myself to myself, but even around people in the same situation in that hospital, I found that I couldn't try to keep pace or set pace with them as well, and I was left with really only one choice and that was to focus on who I was at that point in time, with where I needed to go and to get back to who I needed to be.</p>
<p>For the next six weeks, for seven to eight hours a day, that's what I did. I built little by little, and, as you might expect, when you're recovering from a spinal cord injury, you're going to have a bad day. You might have a few in a row. What I found out is that good and bad really didn't have a lot of meaning, unless I had the context of knowing what my average was.</p>
<p>It was really up to me to decide if something was bad or good, based on where I was at that point in time, and it was in my control to determine if it really was bad day. In fact, it was my decision on whether or not I could stop a streak of bad days.</p>
<p>And what I found during that time away from home is I never had a bad day, even with everything going on. There were parts of my day that certainly not as pleasant as they could be, but it was never an entirely bad day.</p>
<p>So I'm guessing that all of you have been through a meeting that probably didn't go very well, or a commute that wasn't as great as you would like it, or even burned dinner at night. Did those things really ruin your entire day?</p>
<p>What I found in those scenarios is the quicker you move on to what's next, the quicker you can start attacking things. And by moving on to next as fast as possible, you shrink the time you spend in those bad scenarios, and it gives more time for the good. And, as a result, the good outweight the bad, your average increases and that's just how the math works.</p>
<p>It didn't matter to me if I'd spent the morning really struggling with my medication, or at lunch my legs being very spastic, or even if I had fallen out of my wheelchair. Ask my wife, it happens quite often. She's here. They were just small parts of my day and small parts of my average.</p>
<p>And so, in the months and years that followed, I continued to try to attack things in that way, and before I knew it I was being presented with some pretty incredible challenges, like completing a marathon in a wheelchair.</p>
<p>In early 2016, I met my physical therapist, and after a few really grueling sessions, she must have sensed something, because she pulled me aside and said, &quot;You know, you should do a half marathon. In your wheelchair. And, oh yeah, it's in 10 weeks.&quot;</p>
<p>And I thought in my mind, &quot;You're crazy.&quot; I didn't have a workout plan. I didn't have any way of knowing how fast I needed to go, or how far I was supposed to go. But I simply got to work, and I started tracking every workout, every day, and I simply wanted to be as good as or as fast as I was the prior day.</p>
<p>And in the end I really created that average for myself, and I tried to build on that as much as I could.</p>
<p>Well, I finished that race right in time with what my average should have been, and somewhere along the way, I kind of closed the door on who I once was. That person who I was before, and all those things I thought I was able to do really didn't matter. In fact. walking again really didn't matter.</p>
<p>It became much less of a goal for me in terms of where I was going to go. And besides, like, you guys are so slow when you walk. In crowds like this, it is so difficult. I'm like, &quot;Get out of the way, We're going places.&quot;</p>
<p>And all I wanted to do was go fast. So I did what I thought I should do. I started researching wheelchair racing. And I went online and I found the best of the best, I learned their technique, I learned about the equipment, and I was lucky to have a coach that offered me a way to get started.</p>
<p>And after talking with him, and having him help me get those things underway, as I was leaving, he says, &quot;You know, you should do the 2017 Chicago Marathon.&quot; And he's the coach, I can't tell him no.</p>
<p>So with that guidance, I went back home, and I got to work, much like in the prior way. And I continued researching but I had learned my lesson. I was really carefull not to compare with how accomplished those people on the internet were, and how fast they were, because if I had, I probably never would have continued going through with it.</p>
<p>Well, the weekend of the race arrived, and it was just like going to college for the first time. You're dumped off, there's a whole bunch of people around you, you don't really know very many of them, somebody's got the cool stereo and the cool TV, and they're smart and they're pretty and they're cute and they're handsome, and you don't know if you really belong.</p>
<p>But then somebody says, &quot;Hey, let's go get food.&quot; And all of a sudden, that friend group happens, and you start to settle in.</p>
<p>Well, that weekend of the race, we had a meeting called the Wheelchairs Meeting, and there were 60 wheelchairs in that room the night before the race. And wouldn't you know it, all of the people that I had been researching were there, the best in the world.</p>
<p>There must have been over 50 Paralympic medals in the room that day. And I felt pretty small and I fell back into that trap of comparing myself. I knew that my average that I had been tracking during my workouts were over 90 seconds slower per mile than theirs.</p>
<p>And the coach was the only one there that I knew, and he reached out and noticed something, and I think he sensed my anxiety, and he invited me to get food with his team. And with that, everything settled down. I reallized really quick that they didn't care about my average, surely, and I had forgotten about their.</p>
<p>Well that next day, I finished the race about 45 minutes after the person that won it. But as I was leaving, those new friends, who are very close today, challenged me to stay involved, and to keep working through different races and competitions. And so I did what I knew how. I went home, and I got busy.</p>
<p>Now, as you can imagine, being in a wheelchair, let alone training for a marathon in a wheelchair, is a pretty lonely thing. I have an incredible group of friends that will ride bikes with me and keep track of pace and help me out. But in the end, it's still five to six days a week, it's 50 to 60 miles of effort, and it's a lot of alone time.</p>
<p>And for the most part, you really have nothing to rely on but yourself in those times. It's my average, and I'm trying to get better little by little. Well, this fall I was in Chicago for the third time. It was my seventh marathon, and just like going back to college for your junior year, you're anticipating catching up with friends, and getting excited about rolling right back into things.</p>
<p>Well, I attended the same pre-race meeting and the same pre-race meal, and caught up with those friends. And we lined up for race, and right at the start, my average kicked in, and before long I caught up with some of those friends, and was able to keep pace with them and push together. But it wasn't long before I faded.</p>
<p>It just happened, and I found myself all alone again, with really nothing to rely on other than what I had worked so hard to be at. But we turned into wind at the halfway point, and my average became a strong advantage, and it wasn't long before I caught some of those friends, and passed them all the way to the finish.</p>
<p>And while I didn't set a personal record that day, I did finish 30 seconds per mile faster than my prior Chicago times, and just left myself pretty excited.</p>
<p>And so this is me. This is my average. Seventy-five days from today, I'll be in Bostom for my second time. I'm super excited about that. But keep in mind, this isn't really just about racing. I'm working really hard every day to be better in so many other ways, a better parent, a better husband, a better coach, teammate, friend, person. And I promise you, even though what you see here is very visible in terms of challenges that I face, everybody here has something that they're fighting, and it may be visible, it may not be, but please, take some time and focus on you instead or others, and I bet you can win those challenges, and really start accomplishing so many great things.</p>
<src-rtyAudio :src="'https://rtyxmd.gitee.io/rtyresources2020/July/Stop comparing yourself to others.mp3'"></src-rtyAudio></div></template>
